import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { DatePicker } from '@/components/ui/date-picker';

type RuleField={id:number;label:string;field_type:string};
type ExistingRules={
  validation_rules?:Record<string,unknown>|null;
  comparison_rule?:{source_field_id:number;operator:string}|null;
  copy_rule?:{source_field_id:number;trigger_field_id:number;trigger_values?:string[];read_only?:boolean}|null;
};
const selectClass='h-10 w-full rounded-md border bg-background px-3 text-sm shadow-xs outline-none focus:border-ring focus:ring-[3px] focus:ring-ring/50';

export function FieldAdvancedRules({fieldType,sources,current}:{fieldType:string;sources:RuleField[];current?:ExistingRules}){
  const v=current?.validation_rules??{};
  const textLike=['TEXT','TEXTAREA','EMAIL','PHONE'].includes(fieldType);
  const comparable=['NUMBER','DATE'].includes(fieldType);
  const copySources=sources.filter(f=>!['FILE','IMAGE'].includes(f.field_type));
  const compareSources=sources.filter(f=>f.field_type===fieldType && comparable);
  return <>
    {(textLike||fieldType==='NUMBER')&&<div className="sm:col-span-2 rounded-lg border p-4 space-y-3">
      <div><div className="font-medium">Input validation <span className="text-muted-foreground">(optional)</span></div><p className="text-xs text-muted-foreground">Set limits in the template. The same rules are enforced in the applicant UI and on the backend.</p></div>
      {textLike?<div className="grid gap-3 sm:grid-cols-3"><div><Label>Min characters</Label><Input name="min_length" type="number" min="0" defaultValue={String(v.min_length??'')}/></div><div><Label>Max characters</Label><Input name="max_length" type="number" min="1" defaultValue={String(v.max_length??'')}/></div><div><Label>Exact characters</Label><Input name="exact_length" type="number" min="1" defaultValue={String(v.exact_length??'')}/><p className="mt-1 text-xs text-muted-foreground">Use exact OR min/max.</p></div></div>
      :<div className="grid gap-3 sm:grid-cols-4"><div><Label>Min value</Label><Input name="min_value" type="number" step="any" defaultValue={String(v.min_value??'')}/></div><div><Label>Max value</Label><Input name="max_value" type="number" step="any" defaultValue={String(v.max_value??'')}/></div><div><Label>Decimal places</Label><Input name="decimal_places" type="number" min="0" max="8" defaultValue={String(v.decimal_places??'')}/></div><label className="flex items-center gap-2 pt-7 text-sm"><input type="hidden" name="integer_only" value="0"/><input name="integer_only" type="checkbox" value="1" defaultChecked={Boolean(v.integer_only)}/> Whole number only</label></div>}
    </div>}
    {fieldType==='DATE'&&<div className="sm:col-span-2 rounded-lg border p-4 space-y-3">
      <div><div className="font-medium">Date / age validation <span className="text-muted-foreground">(optional)</span></div><p className="text-xs text-muted-foreground">Dynamic rule for any Date field. Example: DOB must make the applicant at least 18 years old on today or on a configured cutoff date.</p></div>
      <div className="grid gap-3 sm:grid-cols-4"><div><Label>Minimum age (years)</Label><Input name="min_age_years" type="number" min="0" max="150" defaultValue={String(v.min_age_years??'')}/></div><div><Label>Maximum age (years)</Label><Input name="max_age_years" type="number" min="0" max="150" defaultValue={String(v.max_age_years??'')}/></div><div><Label>Calculate age on</Label><select name="age_reference_mode" className={selectClass} defaultValue={String(v.age_reference_mode??'TODAY')}><option value="TODAY">Current date</option><option value="CUSTOM">Custom cutoff date</option></select></div><div><Label>Custom cutoff date</Label><DatePicker id="age_reference_date" name="age_reference_date" defaultValue={String(v.age_reference_date??'')}/><p className="mt-1 text-xs text-muted-foreground">Used only when Custom cutoff date is selected.</p></div></div>
    </div>}
    {comparable&&<div className="sm:col-span-2 rounded-lg border p-4 space-y-3"><div><div className="font-medium">Compare with another field <span className="text-muted-foreground">(optional)</span></div><p className="text-xs text-muted-foreground">Example: Obtained Marks ≤ Total Marks, or From Date ≤ To Date.</p></div><div className="grid gap-3 sm:grid-cols-2"><div><Label>Compare with</Label><select name="compare_field_id" className={selectClass} defaultValue={current?.comparison_rule?.source_field_id??''}><option value="">No cross-field validation</option>{compareSources.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></div><div><Label>Rule</Label><select name="compare_operator" className={selectClass} defaultValue={current?.comparison_rule?.operator??'LTE'}><option value="LT">Must be less than (&lt;)</option><option value="LTE">Must be less than or equal (≤)</option><option value="GT">Must be greater than (&gt;)</option><option value="GTE">Must be greater than or equal (≥)</option><option value="EQ">Must equal (=)</option><option value="NEQ">Must not equal (≠)</option></select></div></div></div>}
    {!['FILE','IMAGE'].includes(fieldType)&&<div className="sm:col-span-2 rounded-lg border p-4 space-y-3"><div><div className="font-medium">Copy value from another field <span className="text-muted-foreground">(optional)</span></div><p className="text-xs text-muted-foreground">Use this for “Permanent Address same as Correspondence Address”. Configure each target field with its matching source and a Yes/No or checkbox trigger.</p></div><div className="grid gap-3 sm:grid-cols-3"><div><Label>Copy from field</Label><select name="copy_source_field_id" className={selectClass} defaultValue={current?.copy_rule?.source_field_id??''}><option value="">No copy behavior</option>{copySources.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></div><div><Label>When field</Label><select name="copy_trigger_field_id" className={selectClass} defaultValue={current?.copy_rule?.trigger_field_id??''}><option value="">Choose trigger</option>{copySources.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></div><div><Label>Has value</Label><Input name="copy_trigger_values" defaultValue={current?.copy_rule?.trigger_values?.join(', ')??''} placeholder="YES"/></div></div><label className="flex items-center gap-2 text-sm"><input type="hidden" name="copy_read_only" value="0"/><input name="copy_read_only" type="checkbox" value="1" defaultChecked={current?.copy_rule?.read_only??true}/> Lock target while copy rule is active</label></div>}
  </>;
}
