import { Form, Head } from '@inertiajs/react';
import { Building2, FileCog, Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Spinner } from '@/components/ui/spinner';

type User={id:number;name:string;email:string};
type Option={id:number;label:string;value:string};
type Field={id:number;label:string;field_key:string;field_type:string;is_required:boolean};
type Step={id:number;title:string;code:string;display_order:number;fields:Field[]};
type Template={id:number;name:string;code:string;governance_mode:string;admission_mode:string;status:string;manager?:User|null;steps:Step[]};
type FeeRule={id:number;name:string;fee_required:boolean;amount:string;currency:string;status:string};
type Props={university:{id:number;name:string;code:string};templates:Template[];users:User[];feeRules:FeeRule[];can:{manage:boolean;fee:boolean}};
const selectClass='h-10 w-full rounded-md border bg-background px-3 text-sm shadow-xs outline-none focus:border-ring focus:ring-[3px] focus:ring-ring/50';

function TemplateDialog({users}:{users:User[]}){return <Dialog><DialogTrigger asChild><Button><Plus/>New University Base</Button></DialogTrigger><DialogContent className="sm:!max-w-2xl"><DialogHeader><DialogTitle>Create University Base Form</DialogTitle><DialogDescription>University base steps and fields are locked when inherited by Colleges.</DialogDescription></DialogHeader><Form action="/admin/admission-form-setup/templates" method="post">{({processing})=><><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Name</Label><Input name="name" placeholder="University Admission Form 2026-27"/></div><div className="space-y-2"><Label>Code</Label><Input name="code" placeholder="UNIV_ADM_2026"/></div><div className="space-y-2"><Label>Governance</Label><select name="governance_mode" className={selectClass} defaultValue="UNIVERSITY_BASE_COLLEGE_EXTENSION"><option value="UNIVERSITY_BASE_COLLEGE_EXTENSION">University Base + College Extension</option><option value="UNIVERSITY_CONTROLLED">University Controlled</option></select></div><div className="space-y-2"><Label>Admission Mode</Label><select name="admission_mode" className={selectClass} defaultValue="BOTH"><option value="BOTH">Regular + Direct</option><option value="REGULAR">Regular only</option><option value="DIRECT">Direct only</option></select></div><div className="space-y-2 sm:col-span-2"><Label>Assigned Manager</Label><select name="manager_user_id" className={selectClass} defaultValue=""><option value="">No specific manager</option>{users.map(u=><option key={u.id} value={u.id}>{u.name} · {u.email}</option>)}</select></div><div className="space-y-2 sm:col-span-2"><Label>Description</Label><textarea name="description" className="min-h-20 w-full rounded-md border bg-background px-3 py-2 text-sm"/></div></div><DialogFooter className="mt-5"><DialogClose asChild><Button type="button" variant="outline">Cancel</Button></DialogClose><Button type="submit" disabled={processing}>{processing&&<Spinner/>}Create Draft</Button></DialogFooter></>}</Form></DialogContent></Dialog>}

function StepDialog({template}:{template:Template}){return <Dialog><DialogTrigger asChild><Button size="sm" variant="outline"><Plus/>Add Step</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Add University Base Step</DialogTitle></DialogHeader><Form action={`/admin/admission-form-setup/templates/${template.id}/steps`} method="post">{({processing})=><><div className="space-y-4"><div><Label>Step Title</Label><Input name="title" placeholder="Personal Details"/></div><div><Label>Step Code</Label><Input name="code" placeholder="PERSONAL_DETAILS"/></div><div><Label>Description</Label><textarea name="description" className="min-h-20 w-full rounded-md border bg-background px-3 py-2 text-sm"/></div></div><DialogFooter className="mt-5"><DialogClose asChild><Button type="button" variant="outline">Cancel</Button></DialogClose><Button type="submit" disabled={processing}>{processing&&<Spinner/>}Add Locked Step</Button></DialogFooter></>}</Form></DialogContent></Dialog>}

function FieldDialog({template,step}:{template:Template;step:Step}){return <Dialog><DialogTrigger asChild><Button size="sm" variant="outline"><Plus/>Add Field</Button></DialogTrigger><DialogContent className="sm:!max-w-2xl"><DialogHeader><DialogTitle>Add University Base Field</DialogTitle><DialogDescription>This field will be locked in College extensions.</DialogDescription></DialogHeader><Form action={`/admin/admission-form-setup/templates/${template.id}/steps/${step.id}/fields`} method="post">{({processing})=><><div className="grid gap-4 sm:grid-cols-2"><div><Label>Label</Label><Input name="label"/></div><div><Label>Field Key</Label><Input name="field_key" placeholder="alternate_mobile"/></div><div><Label>Input Type</Label><select name="field_type" className={selectClass} defaultValue="TEXT"><option value="TEXT">Text</option><option value="NUMBER">Number</option><option value="DATE">Date</option><option value="EMAIL">Email</option><option value="PHONE">Phone</option><option value="TEXTAREA">Textarea</option><option value="SELECT">Dropdown</option><option value="RADIO">Radio</option><option value="CHECKBOX">Checkbox</option><option value="MULTISELECT">Multi-select</option><option value="YES_NO">Yes / No</option><option value="FILE">Document/File</option><option value="IMAGE">Image</option></select></div><div><Label>Required?</Label><select name="is_required" className={selectClass} defaultValue="0"><option value="0">Optional</option><option value="1">Required</option></select></div><div className="sm:col-span-2"><Label>Options</Label><textarea name="options" className="min-h-20 w-full rounded-md border bg-background px-3 py-2 text-sm" placeholder="Yes, No or one option per line"/></div><div><Label>Placeholder</Label><Input name="placeholder"/></div><div><Label>Help Text</Label><Input name="help_text"/></div><div><Label>File Max KB</Label><Input name="max_kb" type="number"/></div><div><Label>Allowed Extensions</Label><Input name="extensions" placeholder="pdf,jpg,png"/></div></div><DialogFooter className="mt-5"><DialogClose asChild><Button type="button" variant="outline">Cancel</Button></DialogClose><Button type="submit" disabled={processing}>{processing&&<Spinner/>}Add Locked Field</Button></DialogFooter></>}</Form></DialogContent></Dialog>}

export default function UniversityAdmissionFormSetup({university,templates,users,feeRules,can}:Props){return <><Head title="Admission Form Setup"/><div className="space-y-6 p-4 md:p-6"><header className="flex flex-wrap items-end justify-between gap-3 border-b pb-5"><div><p className="text-sm font-medium text-primary">{university.code} · University Governance</p><h1 className="text-3xl font-semibold">Admission Form Setup</h1><p className="max-w-4xl text-sm text-muted-foreground">Create University base forms and control whether Colleges may extend them. College access itself is governed by the normal Role → Permission → College Scope model.</p></div>{can.manage&&<TemplateDialog users={users}/>}</header>

<div className="space-y-4">{templates.length===0?<Card><CardContent className="grid place-items-center py-12 text-center"><FileCog className="size-9 text-muted-foreground"/><h2 className="mt-3 font-semibold">No University base template yet</h2></CardContent></Card>:templates.map(t=><Card key={t.id}><CardHeader><div className="flex flex-wrap justify-between gap-3"><div><CardTitle>{t.name}</CardTitle><p className="text-sm text-muted-foreground">{t.code} · {t.status} · {t.governance_mode.replaceAll('_',' ')} · {t.admission_mode}</p></div><div className="flex gap-2">{can.manage&&<StepDialog template={t}/>} {can.manage&&t.status!=='ACTIVE'&&<Form action={`/admin/admission-form-setup/templates/${t.id}/status`} method="patch"><input type="hidden" name="status" value="ACTIVE"/><Button size="sm" type="submit">Activate</Button></Form>}</div></div></CardHeader><CardContent className="space-y-3">{t.steps.map(step=><div key={step.id} className="rounded-lg border p-3"><div className="flex justify-between gap-3"><div><div className="font-medium">{step.title}</div><p className="text-xs text-muted-foreground">{step.code} · Locked University base step</p></div>{can.manage&&<FieldDialog template={t} step={step}/>}</div><div className="mt-3 grid gap-2 md:grid-cols-2">{step.fields.map(f=><div key={f.id} className="rounded-md border bg-muted/20 p-3"><div className="font-medium">{f.label}</div><p className="text-xs text-muted-foreground">{f.field_key} · {f.field_type}{f.is_required?' · Required':''} · Locked</p></div>)}</div></div>)}</CardContent></Card>)}</div>

<Card><CardHeader><CardTitle>University Default Application Fee</CardTitle></CardHeader><CardContent className="space-y-4">{can.fee&&<Form action="/admin/admission-form-setup/fee-rules" method="post">{({processing})=><div className="grid items-end gap-3 md:grid-cols-[1.4fr_.7fr_.8fr_.5fr_auto]"><div><Label>Rule Name</Label><Input name="name" placeholder="University default application fee"/></div><div><Label>Fee Required?</Label><select name="fee_required" className={selectClass} defaultValue="1"><option value="1">Yes</option><option value="0">No / Free</option></select></div><div><Label>Amount</Label><Input name="amount" type="number" step="0.01" defaultValue="0"/></div><div><Label>Currency</Label><Input name="currency" defaultValue="INR" maxLength={3}/></div><Button type="submit" disabled={processing}>{processing&&<Spinner/>}Save Default</Button></div>}</Form>}<div className="space-y-2">{feeRules.map(r=><div key={r.id} className="flex justify-between rounded-md border p-3"><div><div className="font-medium">{r.name}</div><p className="text-xs text-muted-foreground">{r.status}</p></div><div className="font-semibold">{r.fee_required?`${r.currency} ${Number(r.amount).toFixed(2)}`:'FREE'}</div></div>)}</div></CardContent></Card>
</div></>}
