import { Head, router } from '@inertiajs/react';
import { useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';

const selectClass='h-9 w-full rounded-md border border-input bg-background px-3 text-sm shadow-sm outline-none focus-visible:ring-1 focus-visible:ring-ring';
const money=(v:string|number,c='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency:c,minimumFractionDigits:2}).format(Number(v||0));
const niceDate=(v?:string|null)=>v?new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${v.slice(0,10)}T00:00:00`)):'—';

type Session={id:number;name:string;code:string;is_current:boolean};
type Student={admission_id:number;admission_no:string|null;candidate_name:string|null;application_no:string|null;email:string|null;phone:string|null;program:string|null;program_code:string|null;session:string|null;demand_count:number;currency:string;debits:string;credits:string;balance:string};
type Page<T>={data:T[];current_page:number;last_page:number;from:number|null;to:number|null;total:number;prev_page_url:string|null;next_page_url:string|null};
type Entry={date:string;type:'DEMAND'|'BENEFIT'|'LATE_FINE'|'PAYMENT'|'ADJUSTMENT'|'REFUND'|'REVERSAL';label:string;reference:string|null;description:string;debit:string;credit:string;balance:string;fee_demand_id:number;fee_demand_item_id:number;due_date:string|null;meta:Record<string,unknown>};
type Ledger={student:{admission_id:number;admission_no:string|null;candidate_name:string|null;application_no:string|null;email:string|null;phone:string|null;program:string|null;program_code:string|null;session:string|null};summary:{currency:string;debits:string;credits:string;balance:string;demand_count:number;entry_count:number};entries:Entry[]};
type Props={college:{id:number;name:string;code:string};sessions:Session[];students:Page<Student>;ledger:Ledger|null;filters:{session_id:number;q:string;per_page:number;admission_id:number|null}};

function typeBadge(entry:Entry){
 const label=entry.type==='DEMAND'?'Demand'
  :entry.type==='BENEFIT'?'Benefit'
  :entry.type==='LATE_FINE'?'Late Fine'
  :entry.type==='PAYMENT'?'Payment'
  :entry.type==='REFUND'?'Refund'
  :entry.label;
 return <Badge variant="outline">{label}</Badge>;
}

export default function Index({college,sessions,students,ledger,filters}:Props){
 const [q,setQ]=useState(filters.q??'');
 const [sessionId,setSessionId]=useState(String(filters.session_id||''));
 const [perPage,setPerPage]=useState(String(filters.per_page||25));
 const search=()=>router.get(`/college/${college.id}/fee-ledger`,{q,session_id:sessionId,per_page:perPage},{preserveState:true,preserveScroll:true});
 const openLedger=(admissionId:number)=>router.get(`/college/${college.id}/fee-ledger`,{q,session_id:sessionId,per_page:perPage,admission_id:admissionId},{preserveState:true,preserveScroll:true});
 return <><Head title="Student Fee Ledger"/><div className="space-y-5 p-4 md:p-6">
  <div><h1 className="text-xl font-semibold">Student Fee Ledger</h1><p className="text-sm text-muted-foreground">A read-only financial statement built from Fee Demands, approved Benefits, Late Fine, payments, adjustments, reversals and refunds.</p></div>
  <Card><CardHeader><CardTitle>Students</CardTitle></CardHeader><CardContent className="space-y-4">
   <div className="grid gap-2 lg:grid-cols-[240px_1fr_100px_auto]"><select className={selectClass} value={sessionId} onChange={e=>setSessionId(e.target.value)}>{sessions.map(s=><option key={s.id} value={s.id}>{s.name}{s.is_current?' · Current':''}</option>)}</select><Input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="Search student / application / admission / demand"/><select className={selectClass} value={perPage} onChange={e=>setPerPage(e.target.value)}>{[25,50,100].map(n=><option key={n} value={n}>{n}</option>)}</select><Button variant="outline" onClick={search}>Search</Button></div>
   <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="border-b bg-muted/30"><tr>{['Student','Application / Admission','Programme','Demands','Total Debit','Total Credit','Balance','Action'].map(x=><th key={x} className="px-3 py-2 text-left font-medium">{x}</th>)}</tr></thead><tbody>{students.data.map(s=><tr key={s.admission_id} className={`border-b ${filters.admission_id===s.admission_id?'bg-muted/20':''}`}><td className="px-3 py-3"><div className="font-medium">{s.candidate_name??'—'}</div><div className="text-xs text-muted-foreground">{s.email??s.phone??''}</div></td><td className="px-3 py-3"><div>{s.application_no??'—'}</div><div className="text-xs text-muted-foreground">{s.admission_no??'—'}</div></td><td className="px-3 py-3"><div>{s.program??'—'}</div><div className="text-xs text-muted-foreground">{s.session??''}</div></td><td className="px-3 py-3">{s.demand_count}</td><td className="px-3 py-3">{money(s.debits,s.currency)}</td><td className="px-3 py-3">{money(s.credits,s.currency)}</td><td className="px-3 py-3 font-semibold">{money(s.balance,s.currency)}</td><td className="px-3 py-3"><Button size="sm" variant={filters.admission_id===s.admission_id?'secondary':'outline'} onClick={()=>openLedger(s.admission_id)}>View Ledger</Button></td></tr>)}{students.data.length===0&&<tr><td colSpan={8} className="px-3 py-8 text-center text-muted-foreground">No students with Fee Demands found for this filter.</td></tr>}</tbody></table></div>
   <div className="flex flex-wrap items-center justify-between gap-2 text-sm"><span>Showing {students.from??0}-{students.to??0} of {students.total} students</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={!students.prev_page_url} onClick={()=>students.prev_page_url&&router.visit(students.prev_page_url)}>Previous</Button><span className="self-center">Page {students.current_page} of {students.last_page}</span><Button size="sm" variant="outline" disabled={!students.next_page_url} onClick={()=>students.next_page_url&&router.visit(students.next_page_url)}>Next</Button></div></div>
  </CardContent></Card>
  {!ledger&&<Card><CardContent className="py-10 text-center text-sm text-muted-foreground">Select a student to view the complete chronological fee ledger.</CardContent></Card>}
  {ledger&&<><Card><CardHeader><CardTitle>{ledger.student.candidate_name} · Fee Statement</CardTitle></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><div className="text-xs text-muted-foreground">Admission</div><div className="font-medium">{ledger.student.admission_no??'—'}</div><div className="text-xs text-muted-foreground">{ledger.student.application_no??'—'}</div></div><div><div className="text-xs text-muted-foreground">Programme</div><div className="font-medium">{ledger.student.program??'—'}</div><div className="text-xs text-muted-foreground">{ledger.student.session??'—'}</div></div><div><div className="text-xs text-muted-foreground">Total Debit</div><div className="text-lg font-semibold">{money(ledger.summary.debits,ledger.summary.currency)}</div><div className="text-xs text-muted-foreground">Demands + active Late Fine</div></div><div><div className="text-xs text-muted-foreground">Outstanding Balance</div><div className="text-lg font-semibold">{money(ledger.summary.balance,ledger.summary.currency)}</div><div className="text-xs text-muted-foreground">After Benefits, Adjustments, Payments, Reversals and Refunds</div></div></div></CardContent></Card>
  <Card><CardHeader><CardTitle>Ledger Entries</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="border-b bg-muted/30"><tr>{['Date','Type','Reference','Description','Due Date','Debit','Credit','Running Balance'].map(x=><th key={x} className="px-3 py-2 text-left font-medium">{x}</th>)}</tr></thead><tbody>{ledger.entries.map((e,i)=><tr key={`${e.type}-${e.fee_demand_item_id}-${e.reference}-${i}`} className="border-b align-top"><td className="px-3 py-3 whitespace-nowrap">{niceDate(e.date)}</td><td className="px-3 py-3">{typeBadge(e)}</td><td className="px-3 py-3"><div className="font-medium">{e.reference??'—'}</div><div className="text-xs text-muted-foreground">Demand #{e.fee_demand_id}</div></td><td className="px-3 py-3"><div>{e.description}</div>{e.type==='PAYMENT'&&e.meta.payment_reference?<div className="text-xs text-muted-foreground">Ref: {String(e.meta.payment_reference)}</div>:null}</td><td className="px-3 py-3 whitespace-nowrap">{niceDate(e.due_date)}</td><td className="px-3 py-3 font-medium">{Number(e.debit)>0?money(e.debit,ledger.summary.currency):'—'}</td><td className="px-3 py-3 font-medium">{Number(e.credit)>0?money(e.credit,ledger.summary.currency):'—'}</td><td className="px-3 py-3 font-semibold">{money(e.balance,ledger.summary.currency)}</td></tr>)}{ledger.entries.length===0&&<tr><td colSpan={8} className="px-3 py-8 text-center text-muted-foreground">No ledger entries exist for this student/session.</td></tr>}</tbody></table></div><p className="mt-3 text-xs text-muted-foreground">Debit increases/restores liability; Credit reduces liability. The ledger includes approved Benefits, posted Payments, Adjustments, Reversals and Refunds. Online gateway transactions appear only after verified posting creates the normal Fee Payment receipt, so they are never double-counted.</p></CardContent></Card></>}
 </div></>;
}
