import { Head, router } from '@inertiajs/react';
import { CheckCircle2, Search, XCircle } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';

type DemandOption = { id:number; demand_no:string; billing_period_label:string; total_amount:string; adjusted_amount:string; outstanding_amount:string; status:string; admission_no:string; application_no:string; candidate_name:string };
type Scheme = { id:number; name:string; code:string; owner_type:string; benefit_type:string; calculation_type:string; benefit_value:string; maximum_benefit_amount:string|null; approval_mode:string; eligibility_mode:string; eligible:boolean; eligibility_reason:string|null; eligible_base_amount:number; calculated_benefit_amount:number; fee_heads:{id:number;name:string;code:string}[] };
type Benefit = { id:number; demand_no:string; admission_no:string; application_no:string; candidate_name:string; billing_period_label:string; scheme_name:string; scheme_code:string; benefit_type:string; application_mode:string; status:string; eligible_base_amount:string; calculated_benefit_amount:string; sanctioned_amount:string|null; application_note:string|null; decision_note:string|null; applied_at:string; decided_at:string|null; demand_total_amount:string; demand_adjusted_amount:string; demand_outstanding_amount:string; eligibility_snapshot?:{reservation_categories?:string[]} };

export default function Page({ college, benefits, can }:{ college:{id:number;name:string;code:string}; benefits:Benefit[]; can:{assign:boolean;approve:boolean;reject:boolean;cancel:boolean} }) {
    const [query,setQuery]=useState(''); const [demandOptions,setDemandOptions]=useState<DemandOption[]>([]); const [selectedDemand,setSelectedDemand]=useState<DemandOption|null>(null);
    const [schemes,setSchemes]=useState<Scheme[]>([]); const [schemeId,setSchemeId]=useState(0); const [note,setNote]=useState(''); const [loading,setLoading]=useState(false); const [search,setSearch]=useState('');
    const [decisionAmounts,setDecisionAmounts]=useState<Record<number,string>>({}); const [decisionNotes,setDecisionNotes]=useState<Record<number,string>>({});
    const money=(value:string|number|null|undefined)=>`₹${Number(value??0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;

    useEffect(()=>{ const q=query.trim(); if(q.length<2){setDemandOptions([]);return;} const controller=new AbortController(); const timer=window.setTimeout(async()=>{ try{ const response=await fetch(`/college/${college.id}/fee-student-benefits/search-demands?q=${encodeURIComponent(q)}`,{signal:controller.signal,headers:{Accept:'application/json'}}); if(!response.ok)throw new Error(); const data=await response.json(); setDemandOptions(data.data??[]);}catch{if(!controller.signal.aborted)setDemandOptions([]);}},250); return()=>{window.clearTimeout(timer);controller.abort();};},[college.id,query]);
    useEffect(()=>{ if(!selectedDemand){setSchemes([]);setSchemeId(0);return;} const controller=new AbortController(); setLoading(true); fetch(`/college/${college.id}/fee-student-benefits/demands/${selectedDemand.id}/schemes`,{signal:controller.signal,headers:{Accept:'application/json'}}).then(r=>r.ok?r.json():Promise.reject()).then(data=>{setSchemes(data.data??[]);setSchemeId(0);}).catch(()=>{if(!controller.signal.aborted)setSchemes([]);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);}); return()=>controller.abort();},[college.id,selectedDemand]);

    const selectedScheme=schemes.find(s=>s.id===schemeId)??null;
    const filteredBenefits=useMemo(()=>{const q=search.trim().toLowerCase(); if(!q)return benefits; return benefits.filter(b=>[b.candidate_name,b.application_no,b.admission_no,b.demand_no,b.scheme_name,b.scheme_code,b.status].some(v=>v?.toLowerCase().includes(q)));},[benefits,search]);
    const assign=()=>{if(!selectedDemand||!selectedScheme?.eligible||!can.assign)return; router.post(`/college/${college.id}/fee-student-benefits`,{fee_demand_id:selectedDemand.id,scheme_id:selectedScheme.id,application_note:note||null},{preserveScroll:true,onSuccess:()=>{setNote('');setSelectedDemand(null);setQuery('');setDemandOptions([]);setSchemes([]);}});};
    const approve=(b:Benefit)=>router.patch(`/college/${college.id}/fee-student-benefits/${b.id}/approve`,{sanctioned_amount:decisionAmounts[b.id]||b.calculated_benefit_amount,decision_note:decisionNotes[b.id]||null},{preserveScroll:true});
    const reject=(b:Benefit)=>{const n=decisionNotes[b.id]?.trim();if(n)router.patch(`/college/${college.id}/fee-student-benefits/${b.id}/reject`,{decision_note:n},{preserveScroll:true});};
    const cancel=(b:Benefit)=>{const n=decisionNotes[b.id]?.trim();if(n)router.patch(`/college/${college.id}/fee-student-benefits/${b.id}/cancel`,{reason:n},{preserveScroll:true});};

    return <><Head title="Student Benefits"/><div className="space-y-4">
        <div><h1 className="text-2xl font-semibold">Student Scholarship / Concession / Waiver</h1><p className="text-sm text-muted-foreground">Assign an ACTIVE eligible scheme, approve/sanction it, and post the approved amount as an auditable Fee Demand adjustment.</p></div>
        {can.assign&&<Card><CardHeader><CardTitle>Assign Benefit to Fee Demand</CardTitle></CardHeader><CardContent className="space-y-4">
            <div className="grid gap-3 md:grid-cols-2"><div className="space-y-2"><label className="text-sm font-medium">Find student / demand</label><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name / Application No / Admission No / Demand No"/></div>{demandOptions.length>0&&!selectedDemand&&<div className="rounded-md border divide-y">{demandOptions.map(d=><button type="button" key={d.id} className="block w-full p-3 text-left hover:bg-muted" onClick={()=>{setSelectedDemand(d);setQuery(`${d.candidate_name} · ${d.demand_no}`);setDemandOptions([]);}}><div className="font-medium">{d.candidate_name} · {d.demand_no}</div><div className="text-xs text-muted-foreground">{d.application_no} · {d.admission_no} · {d.billing_period_label} · Outstanding {money(d.outstanding_amount)}</div></button>)}</div>}</div>
            <div className="space-y-2"><label className="text-sm font-medium">Applicable scheme</label><select className="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm" value={schemeId} onChange={e=>setSchemeId(Number(e.target.value))} disabled={!selectedDemand||loading}><option value={0}>{loading?'Loading applicable schemes...':'Select scheme'}</option>{schemes.map(s=><option key={s.id} value={s.id} disabled={!s.eligible}>{s.name} ({s.code}) — {s.owner_type}{s.eligible?'':' — Not eligible'}</option>)}</select></div></div>
            {selectedDemand&&<div className="grid gap-3 rounded-md border p-3 md:grid-cols-4 text-sm"><div><span className="text-muted-foreground">Candidate</span><div className="font-medium">{selectedDemand.candidate_name}</div></div><div><span className="text-muted-foreground">Demand</span><div className="font-medium">{selectedDemand.demand_no}</div></div><div><span className="text-muted-foreground">Total</span><div className="font-medium">{money(selectedDemand.total_amount)}</div></div><div><span className="text-muted-foreground">Outstanding</span><div className="font-medium">{money(selectedDemand.outstanding_amount)}</div></div></div>}
            {selectedScheme&&<div className="rounded-md border p-3 space-y-2 text-sm"><div className="flex flex-wrap gap-2"><Badge>{selectedScheme.benefit_type}</Badge><Badge variant="outline">{selectedScheme.approval_mode}</Badge><Badge variant="outline">{selectedScheme.owner_type}</Badge></div><div>Fee Heads: {selectedScheme.fee_heads.map(h=>h.name).join(', ')}</div>{selectedScheme.eligible?<div className="grid gap-2 md:grid-cols-2"><div>Eligible base: <strong>{money(selectedScheme.eligible_base_amount)}</strong></div><div>Calculated benefit: <strong>{money(selectedScheme.calculated_benefit_amount)}</strong></div></div>:<div className="text-destructive">{selectedScheme.eligibility_reason}</div>}</div>}
            <Input value={note} onChange={e=>setNote(e.target.value)} placeholder="Application / assignment note (optional)"/><Button onClick={assign} disabled={!selectedScheme?.eligible}>Assign / Apply Benefit</Button>
        </CardContent></Card>}
        <Card><CardHeader><CardTitle>Student Benefit Register</CardTitle></CardHeader><CardContent className="space-y-3"><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search candidate / application / admission / demand / scheme / status"/>{filteredBenefits.length===0&&<p className="text-sm text-muted-foreground">No student benefit records configured.</p>}{filteredBenefits.map(b=><div key={b.id} className="rounded-md border p-4 space-y-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-semibold">{b.candidate_name} · {b.scheme_name} ({b.scheme_code})</div><div className="text-sm text-muted-foreground">{b.application_no} · {b.admission_no} · {b.demand_no} · {b.billing_period_label}</div></div><div className="flex gap-2"><Badge variant="outline">{b.benefit_type}</Badge><Badge>{b.status}</Badge></div></div><div className="grid gap-3 md:grid-cols-4 text-sm"><div><span className="text-muted-foreground">Eligible Base</span><div className="font-medium">{money(b.eligible_base_amount)}</div></div><div><span className="text-muted-foreground">Calculated</span><div className="font-medium">{money(b.calculated_benefit_amount)}</div></div><div><span className="text-muted-foreground">Sanctioned</span><div className="font-medium">{b.sanctioned_amount?money(b.sanctioned_amount):'Pending'}</div></div><div><span className="text-muted-foreground">Demand Outstanding</span><div className="font-medium">{money(b.demand_outstanding_amount)}</div></div></div>{!!b.eligibility_snapshot?.reservation_categories?.length&&<div className="text-xs text-muted-foreground">Admission category snapshot: {b.eligibility_snapshot.reservation_categories.join(', ')}</div>}{b.status==='PENDING'&&<div className="grid gap-2 md:grid-cols-3"><Input value={decisionAmounts[b.id]??b.calculated_benefit_amount} onChange={e=>setDecisionAmounts(v=>({...v,[b.id]:e.target.value}))} placeholder="Sanction amount"/><Input value={decisionNotes[b.id]??''} onChange={e=>setDecisionNotes(v=>({...v,[b.id]:e.target.value}))} placeholder="Decision note / rejection reason"/><div className="flex flex-wrap gap-2">{can.approve&&<Button size="sm" onClick={()=>approve(b)}><CheckCircle2 className="mr-2 h-4 w-4"/>Approve</Button>}{can.reject&&<Button size="sm" variant="outline" onClick={()=>reject(b)} disabled={!decisionNotes[b.id]?.trim()}><XCircle className="mr-2 h-4 w-4"/>Reject</Button>}{can.cancel&&<Button size="sm" variant="outline" onClick={()=>cancel(b)} disabled={!decisionNotes[b.id]?.trim()}>Cancel</Button>}</div></div>}{b.status==='APPROVED'&&<div className="rounded-md border p-3 text-sm">Fee Demand adjustment posted: <strong>{money(b.sanctioned_amount)}</strong>. Original demand remains unchanged; net outstanding reflects the sanctioned benefit.</div>}</div>)}</CardContent></Card>
    </div></>;
}
