import { Head, router } from '@inertiajs/react';
import { useMemo, useState } from 'react';
import { Pencil, Power, PowerOff } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';

type Opt={id:number;name:string;code:string;college_id?:number|null;is_current?:boolean;status?:string};
type Scheme={id:number;college_program_offering_id?:number|null;name:string;code:string;benefit_type:string;calculation_type:string;benefit_value:string;maximum_benefit_amount:string|null;eligibility_mode:string;approval_mode:string;description:string|null;status:string;academic_session?:Opt;program_template?:Opt;offering?:{program_template?:Opt};fee_heads:Opt[];reservation_categories:Opt[]};
type Props={scope:'UNIVERSITY'|'COLLEGE';university:Opt;college?:Opt;schemes:Scheme[];inheritedSchemes:Scheme[];feeHeads:Opt[];sessions:Opt[];programs:Opt[];offerings:Array<{id:number;academic_session_id:number;program_template?:Opt;academic_session?:Opt}>;reservationCategories:Opt[];can:{create:boolean;update:boolean;enable:boolean;disable:boolean}};
const empty={name:'',code:'',academic_session_id:'',program_template_id:'',college_program_offering_id:'',benefit_type:'SCHOLARSHIP',calculation_type:'PERCENTAGE',benefit_value:'',maximum_benefit_amount:'',eligibility_mode:'OPEN',approval_mode:'MANUAL',fee_head_ids:[] as number[],reservation_category_ids:[] as number[],description:''};

export default function FeeScholarships(p:Props){
 const defaultSessionId=String(p.sessions.find(s=>s.is_current)?.id??p.sessions[0]?.id??'');
 const blankForm=()=>({...empty,academic_session_id:defaultSessionId});
 const [form,setForm]=useState(blankForm); const [editing,setEditing]=useState<Scheme|null>(null); const [search,setSearch]=useState('');
 const base=p.scope==='COLLEGE'?`/college/${p.college?.id}/fee-scholarships`:'/admin/fee-scholarships';
 const visible=useMemo(()=>p.schemes.filter(s=>`${s.name} ${s.code} ${s.benefit_type}`.toLowerCase().includes(search.toLowerCase())),[p.schemes,search]);
 const toggle=(key:'fee_head_ids'|'reservation_category_ids',id:number)=>setForm(f=>({...f,[key]:f[key].includes(id)?f[key].filter(x=>x!==id):[...f[key],id]}));
 const submit=()=>{const data={...form,academic_session_id:Number(form.academic_session_id),program_template_id:form.program_template_id?Number(form.program_template_id):null,college_program_offering_id:form.college_program_offering_id?Number(form.college_program_offering_id):null,benefit_value:Number(form.benefit_value),maximum_benefit_amount:form.maximum_benefit_amount?Number(form.maximum_benefit_amount):null}; if(editing) router.patch(`${base}/${editing.id}`,data,{preserveScroll:true}); else router.post(base,data,{preserveScroll:true});};
 const edit=(s:Scheme)=>{setEditing(s);setForm({name:s.name,code:s.code,academic_session_id:String(s.academic_session?.id??''),program_template_id:String(s.program_template?.id??''),college_program_offering_id:String(s.college_program_offering_id??''),benefit_type:s.benefit_type,calculation_type:s.calculation_type,benefit_value:s.benefit_value,maximum_benefit_amount:s.maximum_benefit_amount??'',eligibility_mode:s.eligibility_mode,approval_mode:s.approval_mode,fee_head_ids:s.fee_heads.map(h=>h.id),reservation_category_ids:s.reservation_categories.map(c=>c.id),description:s.description??''});};
 return <>
  <Head title="Scholarship / Fee Benefits" />
  <div className="space-y-6">
   <div><h1 className="text-2xl font-semibold">Scholarship / Concession / Waiver</h1><p className="text-sm text-muted-foreground">Define auditable financial-benefit rules. Reservation category is an eligibility input only; it does not alter the admission roster.</p></div>
   {(p.can.create||editing) && <Card><CardHeader><CardTitle>{editing?'Edit Scheme':'Add Benefit Scheme'}</CardTitle></CardHeader><CardContent className="space-y-4">
    <div className="grid gap-3 md:grid-cols-3"><Input placeholder="Scheme name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Input placeholder="Code" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><select className="h-9 rounded-md border bg-background px-3 text-sm" value={form.academic_session_id} onChange={e=>setForm({...form,academic_session_id:e.target.value,college_program_offering_id:''})}><option value="">Academic Session</option>{p.sessions.map(x=><option key={x.id} value={x.id}>{x.name} ({x.code}){x.is_current?' — Current':''}</option>)}</select></div>
    <div className="grid gap-3 md:grid-cols-3">{p.scope==='UNIVERSITY'?<select className="h-9 rounded-md border bg-background px-3 text-sm" value={form.program_template_id} onChange={e=>setForm({...form,program_template_id:e.target.value})}><option value="">All Programs</option>{p.programs.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>:<select className="h-9 rounded-md border bg-background px-3 text-sm" value={form.college_program_offering_id} onChange={e=>setForm({...form,college_program_offering_id:e.target.value})}><option value="">Program Offering</option>{p.offerings.filter(o=>!form.academic_session_id||o.academic_session_id===Number(form.academic_session_id)).map(o=><option key={o.id} value={o.id}>{o.program_template?.name} — {o.academic_session?.name}</option>)}</select>}
     <select className="h-9 rounded-md border bg-background px-3 text-sm" value={form.benefit_type} onChange={e=>setForm({...form,benefit_type:e.target.value})}><option>SCHOLARSHIP</option><option>CONCESSION</option><option>WAIVER</option></select><select className="h-9 rounded-md border bg-background px-3 text-sm" value={form.approval_mode} onChange={e=>setForm({...form,approval_mode:e.target.value})}><option value="MANUAL">Approval Required</option><option value="AUTOMATIC">Automatic</option></select></div>
    <div className="grid gap-3 md:grid-cols-3"><select className="h-9 rounded-md border bg-background px-3 text-sm" value={form.calculation_type} onChange={e=>setForm({...form,calculation_type:e.target.value})}><option value="PERCENTAGE">Percentage</option><option value="FIXED">Fixed Amount</option></select><Input type="number" min="0" step="0.01" placeholder={form.calculation_type==='PERCENTAGE'?'Benefit %':'Benefit amount'} value={form.benefit_value} onChange={e=>setForm({...form,benefit_value:e.target.value})}/>{form.calculation_type==='PERCENTAGE'?<Input type="number" min="0" step="0.01" placeholder="Maximum benefit (optional)" value={form.maximum_benefit_amount} onChange={e=>setForm({...form,maximum_benefit_amount:e.target.value})}/>:<div/>}</div>
    <div><div className="mb-2 text-sm font-medium">Applicable Fee Heads</div><div className="flex flex-wrap gap-2">{p.feeHeads.map(h=><Button key={h.id} type="button" size="sm" variant={form.fee_head_ids.includes(h.id)?'default':'outline'} onClick={()=>toggle('fee_head_ids',h.id)}>{h.name}{p.scope==='COLLEGE'&&h.college_id?' · College':' · University'}</Button>)}</div></div>
    <div className="space-y-2"><select className="h-9 rounded-md border bg-background px-3 text-sm" value={form.eligibility_mode} onChange={e=>setForm({...form,eligibility_mode:e.target.value})}><option value="OPEN">Open / Non-category based</option><option value="RESERVATION_CATEGORY">Reservation Category based</option></select>{form.eligibility_mode==='RESERVATION_CATEGORY'&&<div className="flex flex-wrap gap-2">{p.reservationCategories.map(c=><Button key={c.id} type="button" size="sm" variant={form.reservation_category_ids.includes(c.id)?'default':'outline'} onClick={()=>toggle('reservation_category_ids',c.id)}>{c.name} ({c.code})</Button>)}</div>}</div>
    <Input placeholder="Description / policy note (optional)" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/>
    <div className="flex gap-2"><Button onClick={submit}>{editing?'Update Scheme':'Create Scheme'}</Button>{editing&&<Button variant="outline" onClick={()=>{setEditing(null);setForm(blankForm())}}>Cancel</Button>}</div>
   </CardContent></Card>}
   <Card><CardHeader><CardTitle>{p.scope==='COLLEGE'?'College Benefit Schemes':'University Benefit Schemes'}</CardTitle></CardHeader><CardContent className="space-y-3"><Input placeholder="Search scheme / code / type" value={search} onChange={e=>setSearch(e.target.value)}/>{visible.length===0?<p className="text-sm text-muted-foreground">No schemes configured.</p>:visible.map(s=><div key={s.id} className="rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-medium">{s.name} <span className="text-muted-foreground">({s.code})</span></div><div className="mt-1 flex flex-wrap gap-2"><Badge variant="outline">{s.benefit_type}</Badge><Badge variant="outline">{s.calculation_type==='PERCENTAGE'?`${s.benefit_value}%`:`₹${s.benefit_value}`}</Badge><Badge variant="outline">{s.approval_mode}</Badge><Badge variant={s.status==='ACTIVE'?'default':'secondary'}>{s.status}</Badge></div></div><div className="flex gap-2">{s.status==='INACTIVE'&&p.can.update&&<Button size="sm" variant="outline" onClick={()=>edit(s)}><Pencil className="size-4" />Edit</Button>}{((s.status==='INACTIVE'&&p.can.enable)||(s.status==='ACTIVE'&&p.can.disable))&&<Button size="sm" variant="outline" onClick={()=>router.patch(`${base}/${s.id}/status`,{status:s.status==='ACTIVE'?'INACTIVE':'ACTIVE'},{preserveScroll:true})}>{s.status==='ACTIVE'?<PowerOff className="size-4" />:<Power className="size-4" />}{s.status==='ACTIVE'?'Deactivate':'Activate'}</Button>}</div></div><div className="mt-3 text-sm text-muted-foreground">Fee Heads: {s.fee_heads.map(h=>h.name).join(', ')} · Eligibility: {s.eligibility_mode==='OPEN'?'Open':s.reservation_categories.map(c=>c.code).join(', ')||'Category based'} · Session: {s.academic_session?.name}</div></div>)}</CardContent></Card>
   {p.scope==='COLLEGE'&&<Card><CardHeader><CardTitle>Inherited University Schemes</CardTitle></CardHeader><CardContent className="space-y-3">{p.inheritedSchemes.length===0?<p className="text-sm text-muted-foreground">No active University schemes are currently available.</p>:p.inheritedSchemes.map(s=><div key={s.id} className="rounded-lg border p-4"><div className="font-medium">{s.name} ({s.code})</div><div className="mt-1 text-sm text-muted-foreground">Read-only · {s.benefit_type} · {s.calculation_type==='PERCENTAGE'?`${s.benefit_value}%`:`₹${s.benefit_value}`} · {s.fee_heads.map(h=>h.name).join(', ')}</div></div>)}</CardContent></Card>}
  </div>
 </>;
}
