<?php

use App\Http\Controllers\AcademicDisciplineController;
use App\Http\Controllers\AcademicSessionController;
use App\Http\Controllers\ApprovalWorkflowController;
use App\Http\Controllers\ApprovalRequestController;
use App\Http\Controllers\CurriculumController;
use App\Http\Controllers\CurriculumStructureController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\AuthorizedSignatoryController;
use App\Http\Controllers\CollegeAuditLogController;
use App\Http\Controllers\CollegeController;
use App\Http\Controllers\CollegeRoleController;
use App\Http\Controllers\CollegeRolePermissionController;
use App\Http\Controllers\CollegeUserController;
use App\Http\Controllers\CollegeUserRoleController;
use App\Http\Controllers\CourseCategoryController;
use App\Http\Controllers\CourseTypeController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\DegreeController;
use App\Http\Controllers\DegreeLevelController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProgramTemplateController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\RolePermissionController;
use App\Http\Controllers\UniversityController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\TestDataCleanupController;
use Illuminate\Support\Facades\Route;

Route::inertia('/', 'welcome')->name('home');

Route::middleware(['auth', 'active', 'verified'])->group(function () {
    Route::inertia('dashboard', 'dashboard')->name('dashboard');
    Route::get('admin/university', [UniversityController::class, 'show'])->name('university.show');
    Route::patch('admin/university/{university}', [UniversityController::class, 'update'])->name('university.update');
    Route::redirect('super-admin/university', '/admin/university');
    Route::get('admin/colleges', [CollegeController::class, 'index'])->name('colleges.index');
    Route::get('admin/colleges/create', [CollegeController::class, 'create'])->name('colleges.create');
    Route::post('admin/colleges', [CollegeController::class, 'store'])->name('colleges.store');
    Route::get('admin/colleges/{college}/edit', [CollegeController::class, 'edit'])->name('colleges.edit');
    Route::patch('admin/colleges/{college}', [CollegeController::class, 'update'])->name('colleges.update');
    Route::patch('admin/colleges/{college}/status', [CollegeController::class, 'status'])->name('colleges.status');
    Route::redirect('super-admin/colleges', '/admin/colleges');
    Route::get('admin/university/signatories', [AuthorizedSignatoryController::class, 'index'])->name('signatories.index');
    Route::get('admin/university/signatories/create', [AuthorizedSignatoryController::class, 'create'])->name('signatories.create');
    Route::post('admin/university/signatories', [AuthorizedSignatoryController::class, 'store'])->name('signatories.store');
    Route::get('admin/university/signatories/{signatory}/edit', [AuthorizedSignatoryController::class, 'edit'])->name('signatories.edit');
    Route::patch('admin/university/signatories/{signatory}', [AuthorizedSignatoryController::class, 'update'])->name('signatories.update');
    Route::patch('admin/university/signatories/{signatory}/status', [AuthorizedSignatoryController::class, 'status'])->name('signatories.status');
    Route::get('admin/users', [UserController::class, 'index'])->name('users.index');
    Route::get('admin/users/create', [UserController::class, 'create'])->name('users.create');
    Route::post('admin/users', [UserController::class, 'store'])->name('users.store');
    Route::get('admin/users/{user}/edit', [UserController::class, 'edit'])->name('users.edit');
    Route::patch('admin/users/{user}', [UserController::class, 'update'])->name('users.update');
    Route::patch('admin/users/{user}/status', [UserController::class, 'status'])->name('users.status');
    Route::post('admin/users/{user}/password-reset', [UserController::class, 'resetPassword'])->name('users.password-reset');
    Route::redirect('super-admin/users', '/admin/users');
    Route::get('admin/users/{user}/roles', [UserRoleController::class, 'edit'])->name('users.roles.edit');
    Route::put('admin/users/{user}/roles', [UserRoleController::class, 'store'])->name('users.roles.store');
    Route::patch('admin/users/{user}/roles/{assignment}/scope', [UserRoleController::class, 'updateScope'])->name('users.roles.scope.update');
    Route::delete('admin/users/{user}/roles/{assignment}', [UserRoleController::class, 'destroy'])->name('users.roles.destroy');
    Route::get('admin/roles', [RoleController::class, 'index'])->name('roles.index');
    Route::get('admin/roles/create', [RoleController::class, 'create'])->name('roles.create');
    Route::post('admin/roles', [RoleController::class, 'store'])->name('roles.store');
    Route::get('admin/roles/{role}/edit', [RoleController::class, 'edit'])->name('roles.edit');
    Route::patch('admin/roles/{role}', [RoleController::class, 'update'])->name('roles.update');
    Route::patch('admin/roles/{role}/status', [RoleController::class, 'status'])->name('roles.status');
    Route::redirect('super-admin/roles', '/admin/roles');
    Route::get('admin/roles/{role}/permissions', [RolePermissionController::class, 'edit'])->name('roles.permissions.edit');
    Route::put('admin/roles/{role}/permissions', [RolePermissionController::class, 'update'])->name('roles.permissions.update');
    Route::get('admin/permissions', [PermissionController::class, 'index'])->name('permissions.index');
    Route::redirect('super-admin/permissions', '/admin/permissions');
    Route::get('admin/audit-logs', [AuditLogController::class, 'index'])->name('audit-logs.index');
    Route::get('admin/system-maintenance/test-data-cleanup', [TestDataCleanupController::class, 'index'])->name('test-data-cleanup.index');
    Route::delete('admin/system-maintenance/test-data-cleanup/curricula/{curriculum}', [TestDataCleanupController::class, 'destroyCurriculum'])->name('test-data-cleanup.curricula.destroy');
    Route::post('admin/system-maintenance/test-data-cleanup/curricula/{curriculum}/reset-approval', [TestDataCleanupController::class, 'resetCurriculumApproval'])->name('test-data-cleanup.curricula.reset-approval');
    Route::delete('admin/system-maintenance/test-data-cleanup/{type}/{id}', [TestDataCleanupController::class, 'destroyMaster'])->name('test-data-cleanup.master.destroy');

    Route::get('admin/academic-sessions', [AcademicSessionController::class, 'index'])->name('academic-sessions.index');
    Route::post('admin/academic-sessions', [AcademicSessionController::class, 'store'])->name('academic-sessions.store');
    Route::patch('admin/academic-sessions/{academicSession}', [AcademicSessionController::class, 'update'])->name('academic-sessions.update');
    Route::patch('admin/academic-sessions/{academicSession}/status', [AcademicSessionController::class, 'status'])->name('academic-sessions.status');
    Route::patch('admin/academic-sessions/{academicSession}/current', [AcademicSessionController::class, 'setCurrent'])->name('academic-sessions.current');
    Route::get('admin/degree-levels', [DegreeLevelController::class, 'index'])->name('degree-levels.index');
    Route::post('admin/degree-levels', [DegreeLevelController::class, 'store'])->name('degree-levels.store');
    Route::patch('admin/degree-levels/{degreeLevel}', [DegreeLevelController::class, 'update'])->name('degree-levels.update');
    Route::patch('admin/degree-levels/{degreeLevel}/status', [DegreeLevelController::class, 'status'])->name('degree-levels.status');
    Route::get('admin/degrees', [DegreeController::class, 'index'])->name('degrees.index');
    Route::post('admin/degrees', [DegreeController::class, 'store'])->name('degrees.store');
    Route::patch('admin/degrees/{degree}', [DegreeController::class, 'update'])->name('degrees.update');
    Route::patch('admin/degrees/{degree}/status', [DegreeController::class, 'status'])->name('degrees.status');
    Route::get('admin/disciplines', [AcademicDisciplineController::class, 'index'])->name('disciplines.index');
    Route::post('admin/disciplines', [AcademicDisciplineController::class, 'store'])->name('disciplines.store');
    Route::patch('admin/disciplines/{discipline}', [AcademicDisciplineController::class, 'update'])->name('disciplines.update');
    Route::patch('admin/disciplines/{discipline}/status', [AcademicDisciplineController::class, 'status'])->name('disciplines.status');
    Route::get('admin/program-templates', [ProgramTemplateController::class, 'index'])->name('program-templates.index');
    Route::post('admin/program-templates', [ProgramTemplateController::class, 'store'])->name('program-templates.store');
    Route::patch('admin/program-templates/{programTemplate}', [ProgramTemplateController::class, 'update'])->name('program-templates.update');
    Route::patch('admin/program-templates/{programTemplate}/status', [ProgramTemplateController::class, 'status'])->name('program-templates.status');
    Route::get('admin/course-categories', [CourseCategoryController::class, 'index'])->name('course-categories.index');
    Route::post('admin/course-categories', [CourseCategoryController::class, 'store'])->name('course-categories.store');
    Route::patch('admin/course-categories/{courseCategory}', [CourseCategoryController::class, 'update'])->name('course-categories.update');
    Route::patch('admin/course-categories/{courseCategory}/status', [CourseCategoryController::class, 'status'])->name('course-categories.status');
    Route::get('admin/course-types', [CourseTypeController::class, 'index'])->name('course-types.index');
    Route::post('admin/course-types', [CourseTypeController::class, 'store'])->name('course-types.store');
    Route::patch('admin/course-types/{courseType}', [CourseTypeController::class, 'update'])->name('course-types.update');
    Route::patch('admin/course-types/{courseType}/status', [CourseTypeController::class, 'status'])->name('course-types.status');
    Route::get('/admin/courses', [CourseController::class, 'index'])->name('courses.index');
    Route::post('/admin/courses', [CourseController::class, 'store'])->name('courses.store');
    Route::patch('/admin/courses/{course}', [CourseController::class, 'update'])->name('courses.update');
    Route::patch('/admin/courses/{course}/status', [CourseController::class, 'updateStatus'])->name('courses.status');
    Route::get('admin/academic-approval/inbox', [ApprovalRequestController::class, 'index'])->name('approval-requests.index');
    Route::post('admin/academic-approval/requests/{approvalRequest}/decision', [ApprovalRequestController::class, 'decide'])->name('approval-requests.decide');
    Route::get('admin/academic-approval/workflows', [ApprovalWorkflowController::class, 'index'])->name('approval-workflows.index');
    Route::post('admin/academic-approval/workflows', [ApprovalWorkflowController::class, 'store'])->name('approval-workflows.store');
    Route::post('admin/academic-approval/workflows/{workflow}/stages', [ApprovalWorkflowController::class, 'storeStage'])->name('approval-workflows.stages.store');
    Route::patch('admin/academic-approval/workflows/{workflow}/status', [ApprovalWorkflowController::class, 'status'])->name('approval-workflows.status');
    Route::get('admin/curricula', [CurriculumController::class, 'index'])->name('curricula.index');
    Route::post('admin/curricula', [CurriculumController::class, 'store'])->name('curricula.store');
    Route::patch('admin/curricula/{curriculum}', [CurriculumController::class, 'update'])->name('curricula.update');
    Route::delete('admin/curricula/{curriculum}', [CurriculumController::class, 'destroy'])->name('curricula.destroy');
    Route::post('admin/curricula/{curriculum}/clone-structure', [CurriculumController::class, 'cloneStructure'])->name('curricula.clone-structure');
    Route::post('admin/curricula/{curriculum}/submit-for-approval', [CurriculumController::class, 'submitForApproval'])->name('curricula.submit-approval');
    Route::patch('admin/curricula/{curriculum}/retire', [CurriculumController::class, 'retire'])->name('curricula.retire');
    Route::patch('admin/curricula/{curriculum}/restore', [CurriculumController::class, 'restore'])->name('curricula.restore');
    Route::get('admin/curricula/{curriculum}/structure/terms', [CurriculumStructureController::class, 'terms'])->name('curricula.structure.terms');
    Route::get('admin/curricula/{curriculum}/clone-targets/{targetCurriculum}/terms', [CurriculumStructureController::class, 'cloneTargetTerms'])->name('curricula.clone-target-terms');
    Route::post('admin/curricula/{curriculum}/structure/terms', [CurriculumStructureController::class, 'storeTerm'])->name('curricula.structure.terms.store');
    Route::post('admin/curricula/{curriculum}/structure/terms/{term}/clone', [CurriculumStructureController::class, 'cloneTerm'])->name('curricula.structure.terms.clone');
    Route::patch('admin/curricula/{curriculum}/structure/terms/{term}', [CurriculumStructureController::class, 'updateTerm'])->name('curricula.structure.terms.update');
    Route::patch('admin/curricula/{curriculum}/structure/terms/{term}/status', [CurriculumStructureController::class, 'statusTerm'])->name('curricula.structure.terms.status');
    Route::delete('admin/curricula/{curriculum}/structure/terms/{term}', [CurriculumStructureController::class, 'deleteTerm'])->name('curricula.structure.terms.delete');
    Route::get('admin/curricula/{curriculum}/structure/terms/{term}/slots', [CurriculumStructureController::class, 'slots'])->name('curricula.structure.slots');
    Route::post('admin/curricula/{curriculum}/structure/terms/{term}/slots', [CurriculumStructureController::class, 'storeSlot'])->name('curricula.structure.slots.store');
    Route::post('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}/clone', [CurriculumStructureController::class, 'cloneSlot'])->name('curricula.structure.slots.clone');
    Route::patch('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}', [CurriculumStructureController::class, 'updateSlot'])->name('curricula.structure.slots.update');
    Route::patch('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}/status', [CurriculumStructureController::class, 'statusSlot'])->name('curricula.structure.slots.status');
    Route::delete('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}', [CurriculumStructureController::class, 'deleteSlot'])->name('curricula.structure.slots.delete');
    Route::get('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}/course-mappings', [CurriculumStructureController::class, 'courseMappings'])->name('curricula.structure.course-mappings');
    Route::get('admin/curricula/{curriculum}/structure/validate', [CurriculumStructureController::class, 'validateStructure'])->name('curricula.structure.validate');
    Route::post('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}/course-mappings', [CurriculumStructureController::class, 'storeCourseMapping'])->name('curricula.structure.course-mappings.store');
    Route::patch('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}/course-mappings/{mapping}', [CurriculumStructureController::class, 'updateCourseMapping'])->name('curricula.structure.course-mappings.update');
    Route::patch('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}/course-mappings/{mapping}/status', [CurriculumStructureController::class, 'statusCourseMapping'])->name('curricula.structure.course-mappings.status');
    Route::delete('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}/course-mappings/{mapping}', [CurriculumStructureController::class, 'deleteCourseMapping'])->name('curricula.structure.course-mappings.delete');
    Route::patch('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}/course-mappings/{mapping}/order', [CurriculumStructureController::class, 'updateCourseMappingOrder'])->name('curricula.structure.course-mappings.order');
    Route::redirect('super-admin/audit-logs', '/admin/audit-logs');
    Route::get('college/{college}/users', [CollegeUserController::class, 'index'])->name('college-users.index');
    Route::get('college/{college}/users/create', [CollegeUserController::class, 'create'])->name('college-users.create');
    Route::post('college/{college}/users', [CollegeUserController::class, 'store'])->name('college-users.store');
    Route::get('college/{college}/users/{user}/edit', [CollegeUserController::class, 'edit'])->name('college-users.edit');
    Route::patch('college/{college}/users/{user}', [CollegeUserController::class, 'update'])->name('college-users.update');
    Route::patch('college/{college}/users/{user}/status', [CollegeUserController::class, 'status'])->name('college-users.status');
    Route::get('college/{college}/audit-logs', [CollegeAuditLogController::class, 'index'])->name('college-audit-logs.index');
    Route::post('college/{college}/users/{user}/password-reset', [CollegeUserController::class, 'resetPassword'])->name('college-users.password-reset');
    Route::get('college/{college}/users/{user}/roles', [CollegeUserRoleController::class, 'edit'])->name('college-users.roles.edit');
    Route::post('college/{college}/users/{user}/roles', [CollegeUserRoleController::class, 'store'])->name('college-users.roles.store');
    Route::delete('college/{college}/users/{user}/roles/{assignment}', [CollegeUserRoleController::class, 'destroy'])->name('college-users.roles.destroy');
    Route::patch('college/{college}/users/{user}/roles/{assignment}/scope', [CollegeUserRoleController::class, 'updateScope'])->name('college-users.roles.scope.update');
    Route::get('college/{college}/roles', [CollegeRoleController::class, 'index'])->name('college-roles.index');
    Route::post('college/{college}/roles', [CollegeRoleController::class, 'store'])->name('college-roles.store');
    Route::get('college/{college}/roles/{role}/edit', [CollegeRoleController::class, 'edit'])->name('college-roles.edit');
    Route::patch('college/{college}/roles/{role}', [CollegeRoleController::class, 'update'])->name('college-roles.update');
    Route::patch('college/{college}/roles/{role}/status', [CollegeRoleController::class, 'status'])->name('college-roles.status');
    Route::get('college/{college}/roles/{role}/permissions', [CollegeRolePermissionController::class, 'edit'])->name('college-roles.permissions.edit');
    Route::put('college/{college}/roles/{role}/permissions', [CollegeRolePermissionController::class, 'update'])->name('college-roles.permissions.update');
});

require __DIR__.'/settings.php';
