<?php

use App\Http\Controllers\AcademicDisciplineController;
use App\Http\Controllers\AcademicCalendarController;
use App\Http\Controllers\AcademicSessionController;
use App\Http\Controllers\AcademicPolicyController;
use App\Http\Controllers\AcademicPolicyApprovalController;
use App\Http\Controllers\AcademicPolicyCreditCompletionRuleController;
use App\Http\Controllers\AcademicPolicyAttendanceRuleController;
use App\Http\Controllers\AcademicPolicyAssessmentExamRuleController;
use App\Http\Controllers\AcademicPolicyGradingRuleController;
use App\Http\Controllers\AcademicPolicyProgressionRuleController;
use App\Http\Controllers\ApprovalWorkflowController;
use App\Http\Controllers\ApprovalRequestController;
use App\Http\Controllers\CurriculumController;
use App\Http\Controllers\CurriculumStructureController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\AuthorizedSignatoryController;
use App\Http\Controllers\CollegeAuditLogController;
use App\Http\Controllers\CollegeController;
use App\Http\Controllers\CollegeBatchController;
use App\Http\Controllers\CollegeSectionController;
use App\Http\Controllers\CollegeAcademicCalendarController;
use App\Http\Controllers\CollegeProgramIntakeController;
use App\Http\Controllers\CollegeReservationController;
use App\Http\Controllers\CollegeAdmissionSelectionRuleController;
use App\Http\Controllers\CollegeAdmissionCycleController;
use App\Http\Controllers\CollegeAdmissionApplicationController;
use App\Http\Controllers\CollegeAdmissionFormSetupController;
use App\Http\Controllers\UniversityAdmissionFormSetupController;
use App\Http\Controllers\CollegeAdmissionScoreController;
use App\Http\Controllers\CollegeAdmissionInterviewController;
use App\Http\Controllers\CollegeAdmissionMeritController;
use App\Http\Controllers\CollegeAdmissionDocumentVerificationController;
use App\Http\Controllers\CollegeAdmissionSeatAllocationController;
use App\Http\Controllers\CollegeAdmissionConfirmationController;
use App\Http\Controllers\ApplicantPortalController;
use App\Http\Controllers\PublicAdmissionApplicationController;
use App\Http\Controllers\StudentPortalController;
use App\Http\Controllers\CollegeProgramOfferingController;
use App\Http\Controllers\CollegeRoleController;
use App\Http\Controllers\CollegeRolePermissionController;
use App\Http\Controllers\CollegeUserController;
use App\Http\Controllers\CollegeUserRoleController;
use App\Http\Controllers\CourseCategoryController;
use App\Http\Controllers\CourseTypeController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\DegreeController;
use App\Http\Controllers\DegreeLevelController;
use App\Http\Controllers\FeeManagementController;
use App\Http\Controllers\CollegeFeeDemandController;
use App\Http\Controllers\CollegeFeeInstallmentController;
use App\Http\Controllers\CollegeFeeLateFineController;
use App\Http\Controllers\CollegeFeePaymentController;
use App\Http\Controllers\CollegePaymentGatewayController;
use App\Http\Controllers\CollegeOnlinePaymentController;
use App\Http\Controllers\CollegeFeeStudentBenefitController;
use App\Http\Controllers\FeeScholarshipController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProgramTemplateController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ReservationCategoryController;
use App\Http\Controllers\RolePermissionController;
use App\Http\Controllers\UniversityController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\TestDataCleanupController;
use App\Http\Controllers\GatewayTestOrderCleanupController;
use Illuminate\Support\Facades\Route;

Route::inertia('/', 'welcome')->name('home');

Route::get('/apply/{slug}', [ApplicantPortalController::class, 'gateway'])->name('applicant.gateway');
Route::post('/apply/{slug}/register', [ApplicantPortalController::class, 'register'])->name('applicant.register');
Route::post('/apply/{slug}/login', [ApplicantPortalController::class, 'login'])->name('applicant.login');
Route::get('/apply/{slug}/verify-email', [ApplicantPortalController::class, 'verificationNotice'])->name('applicant.verify.notice');
Route::get('/apply/{slug}/verify-email/{id}/{hash}', [ApplicantPortalController::class, 'verifyEmail'])->middleware('signed')->name('applicant.verify.confirm');
Route::post('/apply/{slug}/verify-email/resend', [ApplicantPortalController::class, 'resendVerification'])->middleware('throttle:6,1')->name('applicant.verify.resend');
Route::post('/apply/{slug}/logout', [ApplicantPortalController::class, 'logout'])->name('applicant.logout');
Route::get('/apply/{slug}/application', [PublicAdmissionApplicationController::class, 'show'])->name('applicant.application');
Route::post('/apply/{slug}/application', [PublicAdmissionApplicationController::class, 'store'])->name('applicant.application.store');
Route::get('/student', [StudentPortalController::class, 'index'])->middleware('auth')->name('student.portal');



Route::middleware(['auth', 'active', 'verified'])->group(function () {
    Route::inertia('dashboard', 'dashboard')->name('dashboard');
    Route::get('admin/fee-management', [FeeManagementController::class, 'universityIndex'])->name('fee-management.university.index');
    Route::get('admin/fee-scholarships', [FeeScholarshipController::class, 'universityIndex'])->name('fee-scholarships.university.index');
    Route::post('admin/fee-scholarships', [FeeScholarshipController::class, 'storeUniversity'])->name('fee-scholarships.university.store');
    Route::patch('admin/fee-scholarships/{scheme}', [FeeScholarshipController::class, 'updateUniversity'])->name('fee-scholarships.university.update');
    Route::patch('admin/fee-scholarships/{scheme}/status', [FeeScholarshipController::class, 'statusUniversity'])->name('fee-scholarships.university.status');
    Route::post('admin/fee-management/categories', [FeeManagementController::class, 'storeUniversityCategory'])->name('fee-management.university.categories.store');
    Route::patch('admin/fee-management/categories/{category}', [FeeManagementController::class, 'updateUniversityCategory'])->name('fee-management.university.categories.update');
    Route::patch('admin/fee-management/categories/{category}/status', [FeeManagementController::class, 'statusUniversityCategory'])->name('fee-management.university.categories.status');
    Route::post('admin/fee-management/heads', [FeeManagementController::class, 'storeUniversityHead'])->name('fee-management.university.heads.store');
    Route::patch('admin/fee-management/heads/{head}', [FeeManagementController::class, 'updateUniversityHead'])->name('fee-management.university.heads.update');
    Route::patch('admin/fee-management/heads/{head}/status', [FeeManagementController::class, 'statusUniversityHead'])->name('fee-management.university.heads.status');
    Route::post('admin/fee-management/structures', [FeeManagementController::class, 'storeUniversityStructure'])->name('fee-management.university.structures.store');
    Route::patch('admin/fee-management/structures/{structure}', [FeeManagementController::class, 'updateUniversityStructure'])->name('fee-management.university.structures.update');
    Route::patch('admin/fee-management/structures/{structure}/status', [FeeManagementController::class, 'statusUniversityStructure'])->name('fee-management.university.structures.status');
    Route::post('admin/fee-management/structures/{structure}/items', [FeeManagementController::class, 'storeUniversityItem'])->name('fee-management.university.items.store');
    Route::patch('admin/fee-management/structures/{structure}/items/{item}', [FeeManagementController::class, 'updateUniversityItem'])->name('fee-management.university.items.update');
    Route::delete('admin/fee-management/structures/{structure}/items/{item}', [FeeManagementController::class, 'destroyUniversityItem'])->name('fee-management.university.items.destroy');
    Route::get('admin/university', [UniversityController::class, 'show'])->name('university.show');
    Route::patch('admin/university/{university}', [UniversityController::class, 'update'])->name('university.update');
    Route::redirect('super-admin/university', '/admin/university');
    Route::get('admin/colleges', [CollegeController::class, 'index'])->name('colleges.index');
    Route::get('admin/colleges/create', [CollegeController::class, 'create'])->name('colleges.create');
    Route::post('admin/colleges', [CollegeController::class, 'store'])->name('colleges.store');
    Route::get('admin/colleges/{college}/edit', [CollegeController::class, 'edit'])->name('colleges.edit');
    Route::patch('admin/colleges/{college}', [CollegeController::class, 'update'])->name('colleges.update');
    Route::patch('admin/colleges/{college}/status', [CollegeController::class, 'status'])->name('colleges.status');
    Route::get('admin/admission-form-setup', [UniversityAdmissionFormSetupController::class, 'index'])->name('university-admission-form-setup.index');
    Route::post('admin/admission-form-setup/templates', [UniversityAdmissionFormSetupController::class, 'storeTemplate'])->name('university-admission-form-setup.templates.store');
    Route::patch('admin/admission-form-setup/templates/{template}', [UniversityAdmissionFormSetupController::class, 'updateTemplate'])->name('university-admission-form-setup.templates.update');
    Route::delete('admin/admission-form-setup/templates/{template}', [UniversityAdmissionFormSetupController::class, 'destroyTemplate'])->name('university-admission-form-setup.templates.destroy');
    Route::patch('admin/admission-form-setup/templates/{template}/override-control', [UniversityAdmissionFormSetupController::class, 'overrideControl'])->name('university-admission-form-setup.templates.override-control');
    Route::patch('admin/admission-form-setup/templates/{template}/status', [UniversityAdmissionFormSetupController::class, 'statusTemplate'])->name('university-admission-form-setup.templates.status');
    Route::patch('admin/admission-form-setup/templates/{template}/steps/{step}', [UniversityAdmissionFormSetupController::class, 'updateStep'])->name('university-admission-form-setup.steps.update');
    Route::delete('admin/admission-form-setup/templates/{template}/steps/{step}', [UniversityAdmissionFormSetupController::class, 'destroyStep'])->name('university-admission-form-setup.steps.destroy');
    Route::post('admin/admission-form-setup/templates/{template}/steps/{step}/panels', [UniversityAdmissionFormSetupController::class, 'storePanel'])->name('university-admission-form-setup.panels.store');
    Route::patch('admin/admission-form-setup/templates/{template}/steps/{step}/panels/{panel}', [UniversityAdmissionFormSetupController::class, 'updatePanel'])->name('university-admission-form-setup.panels.update');
    Route::delete('admin/admission-form-setup/templates/{template}/steps/{step}/panels/{panel}', [UniversityAdmissionFormSetupController::class, 'destroyPanel'])->name('university-admission-form-setup.panels.destroy');
    Route::post('admin/admission-form-setup/templates/{template}/steps', [UniversityAdmissionFormSetupController::class, 'storeStep'])->name('university-admission-form-setup.steps.store');
    Route::post('admin/admission-form-setup/templates/{template}/steps/{step}/fields', [UniversityAdmissionFormSetupController::class, 'storeField'])->name('university-admission-form-setup.fields.store');
    Route::patch('admin/admission-form-setup/templates/{template}/steps/{step}/fields/{field}', [UniversityAdmissionFormSetupController::class, 'updateField'])->name('university-admission-form-setup.fields.update');
    Route::delete('admin/admission-form-setup/templates/{template}/steps/{step}/fields/{field}', [UniversityAdmissionFormSetupController::class, 'destroyField'])->name('university-admission-form-setup.fields.destroy');
    Route::post('admin/admission-form-setup/fee-rules', [UniversityAdmissionFormSetupController::class, 'storeFeeRule'])->name('university-admission-form-setup.fee-rules.store');
    Route::redirect('super-admin/colleges', '/admin/colleges');
    Route::get('admin/university/signatories', [AuthorizedSignatoryController::class, 'index'])->name('signatories.index');
    Route::get('admin/university/signatories/create', [AuthorizedSignatoryController::class, 'create'])->name('signatories.create');
    Route::post('admin/university/signatories', [AuthorizedSignatoryController::class, 'store'])->name('signatories.store');
    Route::get('admin/university/signatories/{signatory}/edit', [AuthorizedSignatoryController::class, 'edit'])->name('signatories.edit');
    Route::patch('admin/university/signatories/{signatory}', [AuthorizedSignatoryController::class, 'update'])->name('signatories.update');
    Route::patch('admin/university/signatories/{signatory}/status', [AuthorizedSignatoryController::class, 'status'])->name('signatories.status');
    Route::get('admin/users', [UserController::class, 'index'])->name('users.index');
    Route::get('admin/users/create', [UserController::class, 'create'])->name('users.create');
    Route::post('admin/users', [UserController::class, 'store'])->name('users.store');
    Route::get('admin/users/{user}/edit', [UserController::class, 'edit'])->name('users.edit');
    Route::patch('admin/users/{user}', [UserController::class, 'update'])->name('users.update');
    Route::patch('admin/users/{user}/status', [UserController::class, 'status'])->name('users.status');
    Route::post('admin/users/{user}/password-reset', [UserController::class, 'resetPassword'])->name('users.password-reset');
    Route::redirect('super-admin/users', '/admin/users');
    Route::get('admin/users/{user}/roles', [UserRoleController::class, 'edit'])->name('users.roles.edit');
    Route::put('admin/users/{user}/roles', [UserRoleController::class, 'store'])->name('users.roles.store');
    Route::patch('admin/users/{user}/roles/{assignment}/scope', [UserRoleController::class, 'updateScope'])->name('users.roles.scope.update');
    Route::delete('admin/users/{user}/roles/{assignment}', [UserRoleController::class, 'destroy'])->name('users.roles.destroy');
    Route::get('admin/roles', [RoleController::class, 'index'])->name('roles.index');
    Route::get('admin/roles/create', [RoleController::class, 'create'])->name('roles.create');
    Route::post('admin/roles', [RoleController::class, 'store'])->name('roles.store');
    Route::get('admin/roles/{role}/edit', [RoleController::class, 'edit'])->name('roles.edit');
    Route::patch('admin/roles/{role}', [RoleController::class, 'update'])->name('roles.update');
    Route::patch('admin/roles/{role}/status', [RoleController::class, 'status'])->name('roles.status');
    Route::redirect('super-admin/roles', '/admin/roles');
    Route::get('admin/roles/{role}/permissions', [RolePermissionController::class, 'edit'])->name('roles.permissions.edit');
    Route::put('admin/roles/{role}/permissions', [RolePermissionController::class, 'update'])->name('roles.permissions.update');
    Route::get('admin/permissions', [PermissionController::class, 'index'])->name('permissions.index');
    Route::redirect('super-admin/permissions', '/admin/permissions');
    Route::get('admin/audit-logs', [AuditLogController::class, 'index'])->name('audit-logs.index');
    Route::get('admin/system-maintenance/test-data-cleanup', [TestDataCleanupController::class, 'index'])->name('test-data-cleanup.index');
    Route::delete('admin/system-maintenance/test-data-cleanup/full-reset', [TestDataCleanupController::class, 'fullReset'])->name('test-data-cleanup.full-reset');
    Route::delete('admin/system-maintenance/test-data-cleanup/gateway-test-orders', GatewayTestOrderCleanupController::class)->name('test-data-cleanup.gateway-test-orders');
    Route::delete('admin/system-maintenance/test-data-cleanup/legacy-unlinked-regular-applications', [TestDataCleanupController::class, 'cleanupLegacyUnlinkedRegularApplications'])->name('test-data-cleanup.legacy-unlinked-regular-applications');
    Route::delete('admin/system-maintenance/test-data-cleanup/curricula/{curriculum}', [TestDataCleanupController::class, 'destroyCurriculum'])->name('test-data-cleanup.curricula.destroy');
    Route::post('admin/system-maintenance/test-data-cleanup/curricula/{curriculum}/reset-approval', [TestDataCleanupController::class, 'resetCurriculumApproval'])->name('test-data-cleanup.curricula.reset-approval');
    Route::delete('admin/system-maintenance/test-data-cleanup/academic-policies/{academicPolicy}', [TestDataCleanupController::class, 'destroyAcademicPolicy'])->name('test-data-cleanup.academic-policies.destroy');
    Route::post('admin/system-maintenance/test-data-cleanup/admission-form-templates/{template}/deactivate', [TestDataCleanupController::class, 'deactivateAdmissionFormTemplate'])->name('test-data-cleanup.admission-form-templates.deactivate');
    Route::post('admin/system-maintenance/test-data-cleanup/academic-policies/{academicPolicy}/reset-approval', [TestDataCleanupController::class, 'resetAcademicPolicyApproval'])->name('test-data-cleanup.academic-policies.reset-approval');
    Route::post('admin/system-maintenance/test-data-cleanup/bulk-clean', [TestDataCleanupController::class, 'bulkCleanup'])->name('test-data-cleanup.bulk-clean');
    Route::delete('admin/system-maintenance/test-data-cleanup/{type}/{id}', [TestDataCleanupController::class, 'destroyMaster'])->name('test-data-cleanup.master.destroy');

    Route::get('admin/academic-sessions', [AcademicSessionController::class, 'index'])->name('academic-sessions.index');
    Route::post('admin/academic-sessions', [AcademicSessionController::class, 'store'])->name('academic-sessions.store');
    Route::patch('admin/academic-sessions/{academicSession}', [AcademicSessionController::class, 'update'])->name('academic-sessions.update');
    Route::patch('admin/academic-sessions/{academicSession}/status', [AcademicSessionController::class, 'status'])->name('academic-sessions.status');
    Route::patch('admin/academic-sessions/{academicSession}/current', [AcademicSessionController::class, 'setCurrent'])->name('academic-sessions.current');
    Route::get('admin/academic-calendars', [AcademicCalendarController::class, 'index'])->name('academic-calendars.index');
    Route::post('admin/academic-calendars', [AcademicCalendarController::class, 'store'])->name('academic-calendars.store');
    Route::patch('admin/academic-calendars/{academicCalendar}', [AcademicCalendarController::class, 'update'])->name('academic-calendars.update');
    Route::patch('admin/academic-calendars/{academicCalendar}/status', [AcademicCalendarController::class, 'status'])->name('academic-calendars.status');
    Route::post('admin/academic-calendars/{academicCalendar}/term-periods', [AcademicCalendarController::class, 'storeTermPeriod'])->name('academic-calendars.term-periods.store');
    Route::patch('admin/academic-calendars/{academicCalendar}/term-periods/{period}', [AcademicCalendarController::class, 'updateTermPeriod'])->name('academic-calendars.term-periods.update');
    Route::post('admin/academic-calendars/{academicCalendar}/events', [AcademicCalendarController::class, 'storeEvent'])->name('academic-calendars.events.store');
    Route::patch('admin/academic-calendars/{academicCalendar}/events/{event}', [AcademicCalendarController::class, 'updateEvent'])->name('academic-calendars.events.update');
    Route::patch('admin/academic-calendars/{academicCalendar}/events/{event}/status', [AcademicCalendarController::class, 'eventStatus'])->name('academic-calendars.events.status');
    Route::get('admin/degree-levels', [DegreeLevelController::class, 'index'])->name('degree-levels.index');
    Route::post('admin/degree-levels', [DegreeLevelController::class, 'store'])->name('degree-levels.store');
    Route::patch('admin/degree-levels/{degreeLevel}', [DegreeLevelController::class, 'update'])->name('degree-levels.update');
    Route::patch('admin/degree-levels/{degreeLevel}/status', [DegreeLevelController::class, 'status'])->name('degree-levels.status');
    Route::get('admin/degrees', [DegreeController::class, 'index'])->name('degrees.index');
    Route::post('admin/degrees', [DegreeController::class, 'store'])->name('degrees.store');
    Route::patch('admin/degrees/{degree}', [DegreeController::class, 'update'])->name('degrees.update');
    Route::patch('admin/degrees/{degree}/status', [DegreeController::class, 'status'])->name('degrees.status');
    Route::get('admin/disciplines', [AcademicDisciplineController::class, 'index'])->name('disciplines.index');
    Route::post('admin/disciplines', [AcademicDisciplineController::class, 'store'])->name('disciplines.store');
    Route::patch('admin/disciplines/{discipline}', [AcademicDisciplineController::class, 'update'])->name('disciplines.update');
    Route::patch('admin/disciplines/{discipline}/status', [AcademicDisciplineController::class, 'status'])->name('disciplines.status');
    Route::get('admin/program-templates', [ProgramTemplateController::class, 'index'])->name('program-templates.index');
    Route::post('admin/program-templates', [ProgramTemplateController::class, 'store'])->name('program-templates.store');
    Route::patch('admin/program-templates/{programTemplate}', [ProgramTemplateController::class, 'update'])->name('program-templates.update');
    Route::patch('admin/program-templates/{programTemplate}/status', [ProgramTemplateController::class, 'status'])->name('program-templates.status');
    Route::get('admin/course-categories', [CourseCategoryController::class, 'index'])->name('course-categories.index');
    Route::post('admin/course-categories', [CourseCategoryController::class, 'store'])->name('course-categories.store');
    Route::patch('admin/course-categories/{courseCategory}', [CourseCategoryController::class, 'update'])->name('course-categories.update');
    Route::patch('admin/course-categories/{courseCategory}/status', [CourseCategoryController::class, 'status'])->name('course-categories.status');
    Route::get('admin/course-types', [CourseTypeController::class, 'index'])->name('course-types.index');
    Route::post('admin/course-types', [CourseTypeController::class, 'store'])->name('course-types.store');
    Route::patch('admin/course-types/{courseType}', [CourseTypeController::class, 'update'])->name('course-types.update');
    Route::patch('admin/course-types/{courseType}/status', [CourseTypeController::class, 'status'])->name('course-types.status');
    Route::get('/admin/courses', [CourseController::class, 'index'])->name('courses.index');
    Route::post('/admin/courses', [CourseController::class, 'store'])->name('courses.store');
    Route::patch('/admin/courses/{course}', [CourseController::class, 'update'])->name('courses.update');
    Route::patch('/admin/courses/{course}/status', [CourseController::class, 'updateStatus'])->name('courses.status');
    Route::get('admin/academic-policies', [AcademicPolicyController::class, 'index'])->name('academic-policies.index');
    Route::post('admin/academic-policies', [AcademicPolicyController::class, 'store'])->name('academic-policies.store');
    Route::patch('admin/academic-policies/{academicPolicy}', [AcademicPolicyController::class, 'update'])->name('academic-policies.update');
    Route::post('admin/academic-policies/{academicPolicy}/validate', [AcademicPolicyController::class, 'validatePolicy'])->name('academic-policies.validate');
    Route::post('admin/academic-policies/{academicPolicy}/submit-for-approval', [AcademicPolicyController::class, 'submitForApproval'])->name('academic-policies.submit-approval');
    Route::post('admin/academic-policies/{academicPolicy}/amend', [AcademicPolicyController::class, 'amend'])->name('academic-policies.amend');
    Route::post('admin/academic-policies/{academicPolicy}/clone-full', [AcademicPolicyController::class, 'cloneFullPolicy'])->name('academic-policies.clone-full');
    Route::get('admin/academic-policies/approval-inbox', [AcademicPolicyApprovalController::class, 'index'])->name('academic-policies.approval-inbox');
    Route::post('admin/academic-policies/approval-inbox/{approvalRequest}/decision', [AcademicPolicyApprovalController::class, 'decide'])->name('academic-policies.approval-inbox.decision');
    Route::get('admin/academic-policies/{academicPolicy}/credit-completion', [AcademicPolicyCreditCompletionRuleController::class, 'edit'])->name('academic-policies.credit-completion.edit');
    Route::put('admin/academic-policies/{academicPolicy}/credit-completion', [AcademicPolicyCreditCompletionRuleController::class, 'update'])->name('academic-policies.credit-completion.update');
    Route::get('admin/academic-policies/{academicPolicy}/attendance', [AcademicPolicyAttendanceRuleController::class, 'edit'])->name('academic-policies.attendance.edit');
    Route::put('admin/academic-policies/{academicPolicy}/attendance', [AcademicPolicyAttendanceRuleController::class, 'update'])->name('academic-policies.attendance.update');
    Route::get('admin/academic-policies/{academicPolicy}/assessment-examination', [AcademicPolicyAssessmentExamRuleController::class, 'edit'])->name('academic-policies.assessment-examination.edit');
    Route::put('admin/academic-policies/{academicPolicy}/assessment-examination', [AcademicPolicyAssessmentExamRuleController::class, 'update'])->name('academic-policies.assessment-examination.update');
    Route::get('admin/academic-policies/{academicPolicy}/grading', [AcademicPolicyGradingRuleController::class, 'edit'])->name('academic-policies.grading.edit');
    Route::put('admin/academic-policies/{academicPolicy}/grading', [AcademicPolicyGradingRuleController::class, 'update'])->name('academic-policies.grading.update');
    Route::get('admin/academic-policies/{academicPolicy}/progression', [AcademicPolicyProgressionRuleController::class, 'edit'])->name('academic-policies.progression.edit');
    Route::put('admin/academic-policies/{academicPolicy}/progression', [AcademicPolicyProgressionRuleController::class, 'update'])->name('academic-policies.progression.update');
    Route::get('admin/academic-approval/inbox', [ApprovalRequestController::class, 'index'])->name('approval-requests.index');
    Route::post('admin/academic-approval/requests/{approvalRequest}/decision', [ApprovalRequestController::class, 'decide'])->name('approval-requests.decide');
    Route::get('admin/academic-approval/workflows', [ApprovalWorkflowController::class, 'index'])->name('approval-workflows.index');
    Route::post('admin/academic-approval/workflows', [ApprovalWorkflowController::class, 'store'])->name('approval-workflows.store');
    Route::post('admin/academic-approval/workflows/{workflow}/stages', [ApprovalWorkflowController::class, 'storeStage'])->name('approval-workflows.stages.store');
    Route::patch('admin/academic-approval/workflows/{workflow}/status', [ApprovalWorkflowController::class, 'status'])->name('approval-workflows.status');
    Route::get('admin/reservation-categories', [ReservationCategoryController::class, 'index'])->name('reservation-categories.index');
    Route::post('admin/reservation-categories', [ReservationCategoryController::class, 'store'])->name('reservation-categories.store');
    Route::patch('admin/reservation-categories/{reservationCategory}', [ReservationCategoryController::class, 'update'])->name('reservation-categories.update');
    Route::patch('admin/reservation-categories/{reservationCategory}/status', [ReservationCategoryController::class, 'status'])->name('reservation-categories.status');
    Route::get('admin/curricula', [CurriculumController::class, 'index'])->name('curricula.index');
    Route::post('admin/curricula', [CurriculumController::class, 'store'])->name('curricula.store');
    Route::patch('admin/curricula/{curriculum}', [CurriculumController::class, 'update'])->name('curricula.update');
    Route::delete('admin/curricula/{curriculum}', [CurriculumController::class, 'destroy'])->name('curricula.destroy');
    Route::post('admin/curricula/{curriculum}/clone-structure', [CurriculumController::class, 'cloneStructure'])->name('curricula.clone-structure');
    Route::post('admin/curricula/{curriculum}/amend', [CurriculumController::class, 'amend'])->name('curricula.amend');
    Route::post('admin/curricula/{curriculum}/submit-for-approval', [CurriculumController::class, 'submitForApproval'])->name('curricula.submit-approval');
    Route::patch('admin/curricula/{curriculum}/retire', [CurriculumController::class, 'retire'])->name('curricula.retire');
    Route::patch('admin/curricula/{curriculum}/restore', [CurriculumController::class, 'restore'])->name('curricula.restore');
    Route::get('admin/curricula/{curriculum}/structure/terms', [CurriculumStructureController::class, 'terms'])->name('curricula.structure.terms');
    Route::get('admin/curricula/{curriculum}/clone-targets/{targetCurriculum}/terms', [CurriculumStructureController::class, 'cloneTargetTerms'])->name('curricula.clone-target-terms');
    Route::post('admin/curricula/{curriculum}/structure/terms', [CurriculumStructureController::class, 'storeTerm'])->name('curricula.structure.terms.store');
    Route::post('admin/curricula/{curriculum}/structure/terms/{term}/clone', [CurriculumStructureController::class, 'cloneTerm'])->name('curricula.structure.terms.clone');
    Route::patch('admin/curricula/{curriculum}/structure/terms/{term}', [CurriculumStructureController::class, 'updateTerm'])->name('curricula.structure.terms.update');
    Route::patch('admin/curricula/{curriculum}/structure/terms/{term}/status', [CurriculumStructureController::class, 'statusTerm'])->name('curricula.structure.terms.status');
    Route::delete('admin/curricula/{curriculum}/structure/terms/{term}', [CurriculumStructureController::class, 'deleteTerm'])->name('curricula.structure.terms.delete');
    Route::get('admin/curricula/{curriculum}/structure/terms/{term}/slots', [CurriculumStructureController::class, 'slots'])->name('curricula.structure.slots');
    Route::post('admin/curricula/{curriculum}/structure/terms/{term}/slots', [CurriculumStructureController::class, 'storeSlot'])->name('curricula.structure.slots.store');
    Route::post('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}/clone', [CurriculumStructureController::class, 'cloneSlot'])->name('curricula.structure.slots.clone');
    Route::patch('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}', [CurriculumStructureController::class, 'updateSlot'])->name('curricula.structure.slots.update');
    Route::patch('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}/status', [CurriculumStructureController::class, 'statusSlot'])->name('curricula.structure.slots.status');
    Route::delete('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}', [CurriculumStructureController::class, 'deleteSlot'])->name('curricula.structure.slots.delete');
    Route::get('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}/course-mappings', [CurriculumStructureController::class, 'courseMappings'])->name('curricula.structure.course-mappings');
    Route::get('admin/curricula/{curriculum}/structure/validate', [CurriculumStructureController::class, 'validateStructure'])->name('curricula.structure.validate');
    Route::post('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}/course-mappings', [CurriculumStructureController::class, 'storeCourseMapping'])->name('curricula.structure.course-mappings.store');
    Route::patch('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}/course-mappings/{mapping}', [CurriculumStructureController::class, 'updateCourseMapping'])->name('curricula.structure.course-mappings.update');
    Route::patch('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}/course-mappings/{mapping}/status', [CurriculumStructureController::class, 'statusCourseMapping'])->name('curricula.structure.course-mappings.status');
    Route::delete('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}/course-mappings/{mapping}', [CurriculumStructureController::class, 'deleteCourseMapping'])->name('curricula.structure.course-mappings.delete');
    Route::patch('admin/curricula/{curriculum}/structure/terms/{term}/slots/{slot}/course-mappings/{mapping}/order', [CurriculumStructureController::class, 'updateCourseMappingOrder'])->name('curricula.structure.course-mappings.order');
    Route::redirect('super-admin/audit-logs', '/admin/audit-logs');
    Route::get('college/{college}/program-offerings', [CollegeProgramOfferingController::class, 'index'])->name('college-program-offerings.index');
    Route::post('college/{college}/program-offerings', [CollegeProgramOfferingController::class, 'store'])->name('college-program-offerings.store');
    Route::patch('college/{college}/program-offerings/{offering}', [CollegeProgramOfferingController::class, 'update'])->name('college-program-offerings.update');
    Route::patch('college/{college}/program-offerings/{offering}/status', [CollegeProgramOfferingController::class, 'status'])->name('college-program-offerings.status');
    Route::get('college/{college}/batches', [CollegeBatchController::class, 'index'])->name('college-batches.index');
    Route::post('college/{college}/batches', [CollegeBatchController::class, 'store'])->name('college-batches.store');
    Route::patch('college/{college}/batches/{batch}', [CollegeBatchController::class, 'update'])->name('college-batches.update');
    Route::patch('college/{college}/batches/{batch}/status', [CollegeBatchController::class, 'status'])->name('college-batches.status');
    Route::get('college/{college}/sections', [CollegeSectionController::class, 'index'])->name('college-sections.index');
    Route::post('college/{college}/sections', [CollegeSectionController::class, 'store'])->name('college-sections.store');
    Route::patch('college/{college}/sections/{section}', [CollegeSectionController::class, 'update'])->name('college-sections.update');
    Route::patch('college/{college}/sections/{section}/status', [CollegeSectionController::class, 'status'])->name('college-sections.status');
    Route::get('college/{college}/academic-calendar', [CollegeAcademicCalendarController::class, 'index'])->name('college-academic-calendar.index');
    Route::post('college/{college}/academic-calendar', [CollegeAcademicCalendarController::class, 'store'])->name('college-academic-calendar.store');
    Route::patch('college/{college}/academic-calendar/{collegeAcademicCalendar}', [CollegeAcademicCalendarController::class, 'update'])->name('college-academic-calendar.update');
    Route::patch('college/{college}/academic-calendar/{collegeAcademicCalendar}/status', [CollegeAcademicCalendarController::class, 'status'])->name('college-academic-calendar.status');
    Route::post('college/{college}/academic-calendar/{collegeAcademicCalendar}/overrides', [CollegeAcademicCalendarController::class, 'storeOverride'])->name('college-academic-calendar.overrides.store');
    Route::patch('college/{college}/academic-calendar/{collegeAcademicCalendar}/overrides/{override}', [CollegeAcademicCalendarController::class, 'updateOverride'])->name('college-academic-calendar.overrides.update');
    Route::patch('college/{college}/academic-calendar/{collegeAcademicCalendar}/overrides/{override}/status', [CollegeAcademicCalendarController::class, 'overrideStatus'])->name('college-academic-calendar.overrides.status');
    Route::get('college/{college}/intakes', [CollegeProgramIntakeController::class, 'index'])->name('college-program-intakes.index');
    Route::post('college/{college}/intakes', [CollegeProgramIntakeController::class, 'store'])->name('college-program-intakes.store');
    Route::patch('college/{college}/intakes/{intake}', [CollegeProgramIntakeController::class, 'update'])->name('college-program-intakes.update');
    Route::patch('college/{college}/intakes/{intake}/status', [CollegeProgramIntakeController::class, 'status'])->name('college-program-intakes.status');
    Route::post('college/{college}/intakes/{intake}/allocations', [CollegeProgramIntakeController::class, 'storeAllocation'])->name('college-program-intakes.allocations.store');
    Route::patch('college/{college}/intakes/{intake}/allocations/{allocation}', [CollegeProgramIntakeController::class, 'updateAllocation'])->name('college-program-intakes.allocations.update');
    Route::delete('college/{college}/intakes/{intake}/allocations/{allocation}', [CollegeProgramIntakeController::class, 'destroyAllocation'])->name('college-program-intakes.allocations.destroy');
    Route::get('college/{college}/reservations', [CollegeReservationController::class, 'index'])->name('college-reservations.index');
    Route::post('college/{college}/reservations', [CollegeReservationController::class, 'store'])->name('college-reservations.store');
    Route::patch('college/{college}/reservations/{plan}', [CollegeReservationController::class, 'update'])->name('college-reservations.update');
    Route::patch('college/{college}/reservations/{plan}/status', [CollegeReservationController::class, 'status'])->name('college-reservations.status');
    Route::post('college/{college}/reservations/{plan}/allocations', [CollegeReservationController::class, 'storeAllocation'])->name('college-reservations.allocations.store');
    Route::patch('college/{college}/reservations/{plan}/allocations/{allocation}', [CollegeReservationController::class, 'updateAllocation'])->name('college-reservations.allocations.update');
    Route::delete('college/{college}/reservations/{plan}/allocations/{allocation}', [CollegeReservationController::class, 'destroyAllocation'])->name('college-reservations.allocations.destroy');
    Route::get('college/{college}/fee-management', [FeeManagementController::class, 'collegeIndex'])->name('fee-management.college.index');
    Route::post('college/{college}/fee-management/categories', [FeeManagementController::class, 'storeCollegeCategory'])->name('fee-management.college.categories.store');
    Route::patch('college/{college}/fee-management/categories/{category}', [FeeManagementController::class, 'updateCollegeCategory'])->name('fee-management.college.categories.update');
    Route::patch('college/{college}/fee-management/categories/{category}/status', [FeeManagementController::class, 'statusCollegeCategory'])->name('fee-management.college.categories.status');
    Route::post('college/{college}/fee-management/heads', [FeeManagementController::class, 'storeCollegeHead'])->name('fee-management.college.heads.store');
    Route::patch('college/{college}/fee-management/heads/{head}', [FeeManagementController::class, 'updateCollegeHead'])->name('fee-management.college.heads.update');
    Route::patch('college/{college}/fee-management/heads/{head}/status', [FeeManagementController::class, 'statusCollegeHead'])->name('fee-management.college.heads.status');
    Route::post('college/{college}/fee-management/structures', [FeeManagementController::class, 'storeCollegeStructure'])->name('fee-management.college.structures.store');
    Route::patch('college/{college}/fee-management/structures/{structure}', [FeeManagementController::class, 'updateCollegeStructure'])->name('fee-management.college.structures.update');
    Route::patch('college/{college}/fee-management/structures/{structure}/status', [FeeManagementController::class, 'statusCollegeStructure'])->name('fee-management.college.structures.status');
    Route::patch('college/{college}/fee-management/university-structures/{structure}/adoption', [FeeManagementController::class, 'adoptUniversityStructure'])->name('fee-management.college.university-structures.adoption');
    Route::post('college/{college}/fee-management/structures/{structure}/items', [FeeManagementController::class, 'storeCollegeItem'])->name('fee-management.college.items.store');
    Route::patch('college/{college}/fee-management/structures/{structure}/items/{item}', [FeeManagementController::class, 'updateCollegeItem'])->name('fee-management.college.items.update');
    Route::delete('college/{college}/fee-management/structures/{structure}/items/{item}', [FeeManagementController::class, 'destroyCollegeItem'])->name('fee-management.college.items.destroy');
    Route::get('college/{college}/fee-scholarships', [FeeScholarshipController::class, 'collegeIndex'])->name('fee-scholarships.college.index');
    Route::post('college/{college}/fee-scholarships', [FeeScholarshipController::class, 'storeCollege'])->name('fee-scholarships.college.store');
    Route::patch('college/{college}/fee-scholarships/{scheme}', [FeeScholarshipController::class, 'updateCollege'])->name('fee-scholarships.college.update');
    Route::patch('college/{college}/fee-scholarships/{scheme}/status', [FeeScholarshipController::class, 'statusCollege'])->name('fee-scholarships.college.status');
    Route::get('college/{college}/fee-student-benefits', [CollegeFeeStudentBenefitController::class, 'index'])->name('college-fee-student-benefits.index');
    Route::get('college/{college}/fee-student-benefits/search-demands', [CollegeFeeStudentBenefitController::class, 'searchDemands'])->name('college-fee-student-benefits.search-demands');
    Route::get('college/{college}/fee-student-benefits/demands/{demand}/schemes', [CollegeFeeStudentBenefitController::class, 'schemes'])->name('college-fee-student-benefits.schemes');
    Route::get('college/{college}/fee-student-benefits/bulk-schemes', [CollegeFeeStudentBenefitController::class, 'bulkSchemes'])->name('college-fee-student-benefits.bulk-schemes');
    Route::get('college/{college}/fee-student-benefits/bulk-candidates', [CollegeFeeStudentBenefitController::class, 'bulkCandidates'])->name('college-fee-student-benefits.bulk-candidates');
    Route::post('college/{college}/fee-student-benefits/bulk', [CollegeFeeStudentBenefitController::class, 'bulkStore'])->name('college-fee-student-benefits.bulk.store');
    Route::post('college/{college}/fee-student-benefits', [CollegeFeeStudentBenefitController::class, 'store'])->name('college-fee-student-benefits.store');
    Route::patch('college/{college}/fee-student-benefits/{benefit}/approve', [CollegeFeeStudentBenefitController::class, 'approve'])->name('college-fee-student-benefits.approve');
    Route::patch('college/{college}/fee-student-benefits/{benefit}/reject', [CollegeFeeStudentBenefitController::class, 'reject'])->name('college-fee-student-benefits.reject');
    Route::patch('college/{college}/fee-student-benefits/{benefit}/cancel', [CollegeFeeStudentBenefitController::class, 'cancel'])->name('college-fee-student-benefits.cancel');
    Route::get('college/{college}/fee-demands', [CollegeFeeDemandController::class, 'index'])->name('college-fee-demands.index');
    Route::get('college/{college}/fee-demands/eligible-admissions', [CollegeFeeDemandController::class, 'eligibleAdmissions'])->name('college-fee-demands.eligible-admissions');
    Route::post('college/{college}/fee-demands', [CollegeFeeDemandController::class, 'store'])->name('college-fee-demands.store');
    Route::post('college/{college}/fee-demands/bulk', [CollegeFeeDemandController::class, 'bulkStore'])->name('college-fee-demands.bulk.store');
    Route::post('college/{college}/fee-demands/individual', [CollegeFeeDemandController::class, 'individualStore'])->name('college-fee-demands.individual.store');
    Route::patch('college/{college}/fee-demands/{demand}/cancel', [CollegeFeeDemandController::class, 'cancel'])->name('college-fee-demands.cancel');
    Route::post('college/{college}/fee-demands/{demand}/items/{item}/installments', [CollegeFeeInstallmentController::class, 'store'])->name('college-fee-installments.store');
    Route::get('college/{college}/fee-installments/bulk-preview', [CollegeFeeInstallmentController::class, 'bulkPreview'])->name('college-fee-installments.bulk-preview');
    Route::post('college/{college}/fee-installments/bulk', [CollegeFeeInstallmentController::class, 'bulkStore'])->name('college-fee-installments.bulk-store');
    Route::get('college/{college}/payment-gateways', [CollegePaymentGatewayController::class, 'index'])->name('college-payment-gateways.index');
    Route::post('college/{college}/payment-gateways', [CollegePaymentGatewayController::class, 'store'])->name('college-payment-gateways.store');
    Route::patch('college/{college}/payment-gateways/{gateway}', [CollegePaymentGatewayController::class, 'update'])->name('college-payment-gateways.update');
    Route::patch('college/{college}/payment-gateways/{gateway}/status', [CollegePaymentGatewayController::class, 'status'])->name('college-payment-gateways.status');
    Route::post('college/{college}/payment-gateways/{gateway}/mappings', [CollegePaymentGatewayController::class, 'mapping'])->name('college-payment-gateways.mappings.store');
    Route::post('college/{college}/payment-gateways/{gateway}/mappings/bulk', [CollegePaymentGatewayController::class, 'mappingsBulk'])->name('college-payment-gateways.mappings.bulk');
    Route::post('college/{college}/payment-gateways/routing/bulk', [CollegePaymentGatewayController::class, 'routingBulk'])->name('college-payment-gateways.routing.bulk');
    Route::post('college/{college}/payment-gateways/{gateway}/razorpay/test-order', [CollegeOnlinePaymentController::class, 'createRazorpayTestOrder'])->name('college-payment-gateways.razorpay.test-order');
    Route::get('college/{college}/fee-payments', [CollegeFeePaymentController::class, 'index'])->name('college-fee-payments.index');
    Route::post('college/{college}/fee-payments', [CollegeFeePaymentController::class, 'store'])->name('college-fee-payments.store');
    Route::get('college/{college}/fee-late-fines', [CollegeFeeLateFineController::class, 'index'])->name('college-fee-late-fines.index');
    Route::post('college/{college}/fee-late-fines/rules', [CollegeFeeLateFineController::class, 'store'])->name('college-fee-late-fines.rules.store');
    Route::patch('college/{college}/fee-late-fines/rules/{rule}', [CollegeFeeLateFineController::class, 'update'])->name('college-fee-late-fines.rules.update');
    Route::patch('college/{college}/fee-late-fines/rules/{rule}/status', [CollegeFeeLateFineController::class, 'status'])->name('college-fee-late-fines.rules.status');
    Route::delete('college/{college}/fee-late-fines/rules/{rule}', [CollegeFeeLateFineController::class, 'destroyRule'])->name('college-fee-late-fines.rules.destroy');
    Route::post('college/{college}/fee-late-fines/recalculate', [CollegeFeeLateFineController::class, 'recalculate'])->name('college-fee-late-fines.recalculate');
    Route::get('college/{college}/admission-selection-rules', [CollegeAdmissionSelectionRuleController::class, 'index'])->name('college-admission-selection-rules.index');
    Route::post('college/{college}/admission-selection-rules', [CollegeAdmissionSelectionRuleController::class, 'store'])->name('college-admission-selection-rules.store');
    Route::patch('college/{college}/admission-selection-rules/{rule}', [CollegeAdmissionSelectionRuleController::class, 'update'])->name('college-admission-selection-rules.update');
    Route::patch('college/{college}/admission-selection-rules/{rule}/activate', [CollegeAdmissionSelectionRuleController::class, 'activate'])->name('college-admission-selection-rules.activate');
    Route::patch('college/{college}/admission-selection-rules/{rule}/retire', [CollegeAdmissionSelectionRuleController::class, 'retire'])->name('college-admission-selection-rules.retire');
    Route::get('college/{college}/admission-cycles', [CollegeAdmissionCycleController::class, 'index'])->name('college-admission-cycles.index');
    Route::post('college/{college}/admission-cycles', [CollegeAdmissionCycleController::class, 'store'])->name('college-admission-cycles.store');
    Route::patch('college/{college}/admission-cycles/{cycle}', [CollegeAdmissionCycleController::class, 'update'])->name('college-admission-cycles.update');
    Route::patch('college/{college}/admission-cycles/{cycle}/status', [CollegeAdmissionCycleController::class, 'status'])->name('college-admission-cycles.status');
    Route::get('college/{college}/admission-form-setup', [CollegeAdmissionFormSetupController::class, 'index'])->name('college-admission-form-setup.index');
    Route::patch('college/{college}/admission-form-setup/applicant-registration-settings', [CollegeAdmissionFormSetupController::class, 'updateApplicantRegistrationSettings'])->name('college-admission-form-setup.applicant-registration-settings.update');
    Route::post('college/{college}/admission-form-setup/templates', [CollegeAdmissionFormSetupController::class, 'storeTemplate'])->name('college-admission-form-setup.templates.store');
    Route::patch('college/{college}/admission-form-setup/templates/{template}', [CollegeAdmissionFormSetupController::class, 'updateTemplate'])->name('college-admission-form-setup.templates.update');
    Route::delete('college/{college}/admission-form-setup/templates/{template}', [CollegeAdmissionFormSetupController::class, 'destroyTemplate'])->name('college-admission-form-setup.templates.destroy');
    Route::patch('college/{college}/admission-form-setup/templates/{template}/status', [CollegeAdmissionFormSetupController::class, 'statusTemplate'])->name('college-admission-form-setup.templates.status');
    Route::post('college/{college}/admission-form-setup/templates/{template}/steps', [CollegeAdmissionFormSetupController::class, 'storeStep'])->name('college-admission-form-setup.steps.store');
    Route::patch('college/{college}/admission-form-setup/templates/{template}/steps/{step}', [CollegeAdmissionFormSetupController::class, 'updateStep'])->name('college-admission-form-setup.steps.update');
    Route::delete('college/{college}/admission-form-setup/templates/{template}/steps/{step}', [CollegeAdmissionFormSetupController::class, 'destroyStep'])->name('college-admission-form-setup.steps.destroy');
    Route::post('college/{college}/admission-form-setup/templates/{template}/steps/{step}/panels', [CollegeAdmissionFormSetupController::class, 'storePanel'])->name('college-admission-form-setup.panels.store');
    Route::patch('college/{college}/admission-form-setup/templates/{template}/steps/{step}/panels/{panel}', [CollegeAdmissionFormSetupController::class, 'updatePanel'])->name('college-admission-form-setup.panels.update');
    Route::delete('college/{college}/admission-form-setup/templates/{template}/steps/{step}/panels/{panel}', [CollegeAdmissionFormSetupController::class, 'destroyPanel'])->name('college-admission-form-setup.panels.destroy');
    Route::post('college/{college}/admission-form-setup/templates/{template}/steps/{step}/fields', [CollegeAdmissionFormSetupController::class, 'storeField'])->name('college-admission-form-setup.fields.store');
    Route::patch('college/{college}/admission-form-setup/templates/{template}/steps/{step}/fields/{field}', [CollegeAdmissionFormSetupController::class, 'updateField'])->name('college-admission-form-setup.fields.update');
    Route::delete('college/{college}/admission-form-setup/templates/{template}/steps/{step}/fields/{field}', [CollegeAdmissionFormSetupController::class, 'destroyField'])->name('college-admission-form-setup.fields.destroy');
    Route::post('college/{college}/admission-form-setup/templates/{template}/mappings', [CollegeAdmissionFormSetupController::class, 'mapTemplate'])->name('college-admission-form-setup.mappings.store');
    Route::delete('college/{college}/admission-form-setup/templates/{template}/mappings/{mapping}', [CollegeAdmissionFormSetupController::class, 'destroyMapping'])->name('college-admission-form-setup.mappings.destroy');
    Route::patch('college/{college}/admission-form-setup/templates/{template}/mappings/{mapping}/public-access', [CollegeAdmissionFormSetupController::class, 'publicAccess'])->name('college-admission-form-setup.mappings.public-access');
    Route::post('college/{college}/admission-form-setup/fee-rules', [CollegeAdmissionFormSetupController::class, 'storeFeeRule'])->name('college-admission-form-setup.fee-rules.store');
    Route::get('college/{college}/admission-applications', [CollegeAdmissionApplicationController::class, 'index'])->name('college-admission-applications.index');
    Route::post('college/{college}/admission-applications', [CollegeAdmissionApplicationController::class, 'store'])->name('college-admission-applications.store');
    Route::patch('college/{college}/admission-applications/{application}', [CollegeAdmissionApplicationController::class, 'update'])->name('college-admission-applications.update');
    Route::patch('college/{college}/admission-applications/{application}/submit', [CollegeAdmissionApplicationController::class, 'submit'])->name('college-admission-applications.submit');
    Route::patch('college/{college}/admission-application-choices/{choice}/eligibility', [CollegeAdmissionApplicationController::class, 'eligibility'])->name('college-admission-applications.eligibility');
    Route::patch('college/{college}/admission-applications/{application}/withdraw', [CollegeAdmissionApplicationController::class, 'withdraw'])->name('college-admission-applications.withdraw');
    Route::get('college/{college}/admission-scores', [CollegeAdmissionScoreController::class, 'index'])->name('college-admission-scores.index');
    Route::put('college/{college}/admission-application-choices/{choice}/scores', [CollegeAdmissionScoreController::class, 'upsert'])->name('college-admission-scores.upsert');
    Route::get('college/{college}/admission-interviews', [CollegeAdmissionInterviewController::class, 'index'])->name('college-admission-interviews.index');
    Route::post('college/{college}/admission-interview-panels', [CollegeAdmissionInterviewController::class, 'storePanel'])->name('college-admission-interview-panels.store');
    Route::put('college/{college}/admission-application-choices/{choice}/interview', [CollegeAdmissionInterviewController::class, 'upsert'])->name('college-admission-interviews.upsert');
    Route::get('college/{college}/admission-merit', [CollegeAdmissionMeritController::class, 'index'])->name('college-admission-merit.index');
    Route::post('college/{college}/admission-selection-rules/{rule}/merit-roster/generate', [CollegeAdmissionMeritController::class, 'generate'])->name('college-admission-merit.generate');
    Route::get('college/{college}/admission-document-verification', [CollegeAdmissionDocumentVerificationController::class, 'index'])->name('college-admission-document-verification.index');
    Route::get('college/{college}/admission-document-verification/documents/{fieldValue}/download', [CollegeAdmissionDocumentVerificationController::class, 'download'])->name('college-admission-document-verification.download');
    Route::put('college/{college}/admission-document-verification/documents/{fieldValue}', [CollegeAdmissionDocumentVerificationController::class, 'review'])->name('college-admission-document-verification.review');
    Route::patch('college/{college}/admission-document-verification/applications/{application}/finalize', [CollegeAdmissionDocumentVerificationController::class, 'finalize'])->name('college-admission-document-verification.finalize');
    Route::get('college/{college}/admission-seat-allocations', [CollegeAdmissionSeatAllocationController::class, 'index'])->name('college-admission-seat-allocations.index');
    Route::post('college/{college}/admission-seat-allocations/merit/{meritEntry}', [CollegeAdmissionSeatAllocationController::class, 'allocate'])->name('college-admission-seat-allocations.allocate');
    Route::patch('college/{college}/admission-seat-allocations/{allocation}/cancel', [CollegeAdmissionSeatAllocationController::class, 'cancel'])->name('college-admission-seat-allocations.cancel');
    Route::get('college/{college}/admission-confirmations', [CollegeAdmissionConfirmationController::class, 'index'])->name('college-admission-confirmations.index');
    Route::post('college/{college}/admission-confirmations/seat-allocation/{allocation}', [CollegeAdmissionConfirmationController::class, 'confirm'])->name('college-admission-confirmations.confirm');
    Route::patch('college/{college}/admission-confirmations/{admission}/revoke', [CollegeAdmissionConfirmationController::class, 'revoke'])->name('college-admission-confirmations.revoke');
    Route::get('college/{college}/users', [CollegeUserController::class, 'index'])->name('college-users.index');
    Route::get('college/{college}/users/create', [CollegeUserController::class, 'create'])->name('college-users.create');
    Route::post('college/{college}/users', [CollegeUserController::class, 'store'])->name('college-users.store');
    Route::get('college/{college}/users/{user}/edit', [CollegeUserController::class, 'edit'])->name('college-users.edit');
    Route::patch('college/{college}/users/{user}', [CollegeUserController::class, 'update'])->name('college-users.update');
    Route::patch('college/{college}/users/{user}/status', [CollegeUserController::class, 'status'])->name('college-users.status');
    Route::get('college/{college}/audit-logs', [CollegeAuditLogController::class, 'index'])->name('college-audit-logs.index');
    Route::post('college/{college}/users/{user}/password-reset', [CollegeUserController::class, 'resetPassword'])->name('college-users.password-reset');
    Route::get('college/{college}/users/{user}/roles', [CollegeUserRoleController::class, 'edit'])->name('college-users.roles.edit');
    Route::post('college/{college}/users/{user}/roles', [CollegeUserRoleController::class, 'store'])->name('college-users.roles.store');
    Route::delete('college/{college}/users/{user}/roles/{assignment}', [CollegeUserRoleController::class, 'destroy'])->name('college-users.roles.destroy');
    Route::patch('college/{college}/users/{user}/roles/{assignment}/scope', [CollegeUserRoleController::class, 'updateScope'])->name('college-users.roles.scope.update');
    Route::get('college/{college}/roles', [CollegeRoleController::class, 'index'])->name('college-roles.index');
    Route::post('college/{college}/roles', [CollegeRoleController::class, 'store'])->name('college-roles.store');
    Route::get('college/{college}/roles/{role}/edit', [CollegeRoleController::class, 'edit'])->name('college-roles.edit');
    Route::patch('college/{college}/roles/{role}', [CollegeRoleController::class, 'update'])->name('college-roles.update');
    Route::patch('college/{college}/roles/{role}/status', [CollegeRoleController::class, 'status'])->name('college-roles.status');
    Route::get('college/{college}/roles/{role}/permissions', [CollegeRolePermissionController::class, 'edit'])->name('college-roles.permissions.edit');
    Route::put('college/{college}/roles/{role}/permissions', [CollegeRolePermissionController::class, 'update'])->name('college-roles.permissions.update');
});

require __DIR__.'/settings.php';
