import { Head, router } from '@inertiajs/react';
import { CheckCircle2, Download, FileCheck2, FileWarning, ShieldCheck, XCircle } from 'lucide-react';
import { useMemo } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

type Rule = { id:number; name:string; code:string; version_no:number; status:string; bucket_label:string; basis_capacity:number; program_name:string|null; session_name:string|null };
type DocumentRow = { field_value_id:number; label:string|null; field_type:string|null; is_required:boolean; file_name:string|null; file_mime:string|null; file_size:number|null; review:{status:string;remarks:string|null;reviewed_at:string|null}|null };
type Candidate = { application_id:number; application_no:string; candidate_name:string; rank:number; final_weighted_score:number|null; discipline_name:string|null; specialization_name:string|null; verification:{id:number;status:'PENDING'|'VERIFIED'|'DEFICIENT';notes:string|null;finalized_at:string|null}|null; documents:DocumentRow[] };
type Screen = { summary:{total:number;verified:number;pending:number;deficient:number}; rows:Candidate[] }|null;
type Props = { college:{id:number;name:string;code:string;status:string}; rules:Rule[]; selectedRuleId:number|null; screen:Screen; can:{review:boolean;finalize:boolean} };

const badge=(status:string)=>status==='VERIFIED'?'text-emerald-700 border-emerald-300 bg-emerald-50':status==='DEFICIENT'||status==='REJECTED'?'text-destructive border-red-300 bg-red-50':status==='WAIVED'?'text-amber-700 border-amber-300 bg-amber-50':'text-muted-foreground';

export default function CollegeAdmissionDocumentVerification({college,rules,selectedRuleId,screen,can}:Props) {
    const selected=useMemo(()=>rules.find(r=>r.id===selectedRuleId)??null,[rules,selectedRuleId]);
    const choose=(id:number)=>router.get(`/college/${college.id}/admission-document-verification`,{rule_id:id},{preserveState:true,replace:true,preserveScroll:true});
    const review=(doc:DocumentRow,status:'VERIFIED'|'REJECTED'|'WAIVED')=>{
        let remarks:string|null=null;
        if(status!=='VERIFIED') { remarks=window.prompt(status==='REJECTED'?'Reason for rejecting this document:':'Reason/authority for waiving this document:'); if(!remarks?.trim()) return; }
        router.put(`/college/${college.id}/admission-document-verification/documents/${doc.field_value_id}`,{status,remarks:remarks?.trim()??null},{preserveScroll:true});
    };
    const finalize=(candidate:Candidate,status:'VERIFIED'|'DEFICIENT')=>{
        let notes:string|null=null;
        if(status==='DEFICIENT') { notes=window.prompt('Describe the missing/incorrect documents or deficiency:'); if(!notes?.trim()) return; }
        router.patch(`/college/${college.id}/admission-document-verification/applications/${candidate.application_id}/finalize`,{status,notes:notes?.trim()??null},{preserveScroll:true});
    };

    return <><Head title="Admission Document Verification"/><div className="space-y-6 p-4 md:p-6">
        <header className="border-b pb-5"><p className="text-sm font-medium text-primary">{college.code} · Admission Processing</p><h1 className="text-3xl font-semibold">Document Verification</h1><p className="max-w-5xl text-sm text-muted-foreground">Mandatory gate between generated Merit / Roster and Seat Allocation. Review the uploaded admission documents and finalize each ranked application as VERIFIED or DEFICIENT.</p></header>
        {rules.length===0?<Card><CardContent className="p-8 text-center text-sm text-muted-foreground">No generated Merit / Roster is available. Document Verification starts only after a roster is generated.</CardContent></Card>:<div className="grid gap-3 lg:grid-cols-3">{rules.map(rule=><button key={rule.id} onClick={()=>choose(rule.id)} className={`rounded-lg border p-4 text-left ${rule.id===selectedRuleId?'border-primary bg-primary/5':'hover:bg-muted/30'}`}><div className="flex justify-between gap-3"><div><div className="font-semibold">{rule.code} V{rule.version_no}</div><div className="text-xs text-muted-foreground">{rule.name}</div></div><span className="rounded-full border px-2 py-0.5 text-xs">{rule.status}</span></div><div className="mt-3 text-sm">{rule.program_name??'Program'} · {rule.session_name??'Session'}</div><div className="mt-1 text-xs text-muted-foreground">{rule.bucket_label} · Capacity {rule.basis_capacity}</div></button>)}</div>}
        {selected&&screen&&<>
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card><CardContent className="p-4"><div className="text-xs text-muted-foreground">Ranked Applications</div><div className="text-2xl font-semibold">{screen.summary.total}</div></CardContent></Card><Card><CardContent className="p-4"><div className="text-xs text-muted-foreground">Verified</div><div className="text-2xl font-semibold">{screen.summary.verified}</div></CardContent></Card><Card><CardContent className="p-4"><div className="text-xs text-muted-foreground">Pending</div><div className="text-2xl font-semibold">{screen.summary.pending}</div></CardContent></Card><Card><CardContent className="p-4"><div className="text-xs text-muted-foreground">Deficient</div><div className="text-2xl font-semibold">{screen.summary.deficient}</div></CardContent></Card></div>
            <Card><CardHeader><CardTitle className="flex items-center gap-2"><FileCheck2 className="size-5"/>Merit / Roster → Document Verification</CardTitle></CardHeader><CardContent className="space-y-4">{screen.rows.length===0?<div className="py-8 text-center text-sm text-muted-foreground">No ranked applications are available for this rule.</div>:screen.rows.map(candidate=><div key={candidate.application_id} className="rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="font-semibold">Rank #{candidate.rank}</span><span className="font-medium">{candidate.candidate_name}</span><span className={`rounded-full border px-2 py-0.5 text-xs ${badge(candidate.verification?.status??'PENDING')}`}>{candidate.verification?.status??'PENDING'}</span></div><div className="mt-1 text-xs text-muted-foreground">{candidate.application_no} · {candidate.discipline_name??'—'}{candidate.specialization_name?` → ${candidate.specialization_name}`:''} · Score {candidate.final_weighted_score==null?'—':Number(candidate.final_weighted_score).toFixed(3)}</div></div><div className="flex gap-2">{can.finalize&&<><Button size="sm" variant="outline" onClick={()=>finalize(candidate,'DEFICIENT')}><FileWarning/>Mark Deficient</Button><Button size="sm" onClick={()=>finalize(candidate,'VERIFIED')}><ShieldCheck/>Finalize Verified</Button></>}</div></div>
                    {candidate.verification?.notes&&<div className="mt-3 rounded-md bg-muted/40 p-2 text-xs">Notes: {candidate.verification.notes}</div>}
                    <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-muted/30 text-left"><tr><th className="px-3 py-2">Document</th><th className="px-3 py-2">Required</th><th className="px-3 py-2">Review</th><th className="px-3 py-2">Remarks</th><th className="px-3 py-2">Actions</th></tr></thead><tbody>{candidate.documents.length===0?<tr className="border-t"><td colSpan={5} className="px-3 py-4 text-muted-foreground">No FILE / IMAGE fields were uploaded for this application. An authorized staff member must still explicitly finalize the overall verification.</td></tr>:candidate.documents.map(doc=><tr key={doc.field_value_id} className="border-t"><td className="px-3 py-3"><div className="font-medium">{doc.label??'Uploaded document'}</div><div className="text-xs text-muted-foreground">{doc.file_name??'File'}</div></td><td className="px-3 py-3">{doc.is_required?'Yes':'No'}</td><td className="px-3 py-3"><span className={`rounded-full border px-2 py-0.5 text-xs ${badge(doc.review?.status??'PENDING')}`}>{doc.review?.status??'PENDING'}</span></td><td className="max-w-64 px-3 py-3 text-xs text-muted-foreground">{doc.review?.remarks??'—'}</td><td className="px-3 py-3"><div className="flex flex-wrap gap-2"><Button asChild size="sm" variant="outline"><a href={`/college/${college.id}/admission-document-verification/documents/${doc.field_value_id}/download`}><Download/>Open</a></Button>{can.review&&<><Button size="sm" variant="outline" onClick={()=>review(doc,'VERIFIED')}><CheckCircle2/>Verify</Button><Button size="sm" variant="outline" onClick={()=>review(doc,'WAIVED')}>Waive</Button><Button size="sm" variant="outline" onClick={()=>review(doc,'REJECTED')}><XCircle/>Reject</Button></>}</div></td></tr>)}</tbody></table></div>
                </div>)}</CardContent></Card>
        </>}
    </div></>;
}
