import { Head, Link, router, useForm } from '@inertiajs/react';
import { BookOpenCheck, CheckCircle2, ClipboardList, Plus, Send, StopCircle } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { DateTimePicker } from '@/components/ui/date-time-picker';
import { Input } from '@/components/ui/input';
import { SearchableSelect } from '@/components/ui/searchable-select';
import { Spinner } from '@/components/ui/spinner';
import { Textarea } from '@/components/ui/textarea';

type Offering={id:number;batch:{name:string;code:string;offering:{academic_session:{name:string;is_current:boolean}}};curriculum_course_mapping:{course:{name:string;code:string};slot:{term:{name:string}}}};
type Component={id:number;course_offering_id:number;component_type:string;name:string;maximum_marks:string;weightage_percent:string;minimum_pass_marks:string|null;display_order:number;status:string;academic_policy:{code:string;version:number};course_offering:{batch:{name:string};curriculum_course_mapping:{course:{name:string;code:string}}}};
type Allocation={id:number;course_offering_id:number;section_id:number|null;teaching_role:string;faculty:{name:string;email:string}};
type Activity={id:number;status:string;title:string;opens_at:string;closes_at:string;duration_minutes:number|null;component:Component;faculty_allocation:{faculty:{name:string}}};
type Props={college:{id:number;name:string;code:string};mode:'SETUP'|'ASSIGNMENT'|'QUIZ'|'MID_SEMESTER'|'PRACTICAL';offerings:Offering[];components:Component[];allocations:Allocation[];activities:Activity[];can:{setup:boolean;assignment:boolean;quiz:boolean;mid_semester:boolean;practical:boolean}};

export default function InternalAssessment({college,mode,offerings,components,allocations,activities,can}:Props){
 const componentForm=useForm({course_offering_id:'',component_type:'ASSIGNMENT',name:'',maximum_marks:'',weightage_percent:'',minimum_pass_marks:'',display_order:'1',notes:''});
 const activityForm=useForm({internal_assessment_component_id:'',faculty_allocation_id:'',title:'',instructions:'',opens_at:'',closes_at:'',duration_minutes:''});
 const modeComponents=components.filter(c=>mode==='SETUP'||c.component_type===mode);
 const selectedComponent=components.find(c=>String(c.id)===activityForm.data.internal_assessment_component_id);
 const eligibleAllocations=allocations.filter(a=>!selectedComponent||a.course_offering_id===selectedComponent.course_offering_id);
 const createComponent=()=>componentForm.post(`/college/${college.id}/internal-assessment/components`,{preserveScroll:true,onSuccess:()=>componentForm.reset()});
 const createActivity=()=>activityForm.post(`/college/${college.id}/internal-assessment/${mode.toLowerCase()}/activities`,{preserveScroll:true,onSuccess:()=>activityForm.reset()});
 const status=(kind:'components'|'activities',id:number,next:string)=>router.patch(`/college/${college.id}/internal-assessment/${kind}/${id}/status`,{status:next},{preserveScroll:true});
 const canCreateActivity=mode==='ASSIGNMENT'?can.assignment:mode==='QUIZ'?can.quiz:mode==='MID_SEMESTER'?can.mid_semester:can.practical;
 const modeLabel=mode==='MID_SEMESTER'?'Mid Semester':mode==='PRACTICAL'?'Practical':mode==='ASSIGNMENT'?'Assignment':'Quiz';

 return <><Head title={`${college.name} Internal Assessment`}/><div className="space-y-6 p-4 md:p-6">
  <header className="border-b pb-5"><p className="text-sm font-medium text-primary">{college.code} · Internal Assessment</p><h1 className="text-3xl font-semibold">{mode==='SETUP'?'Assessment Setup':`${modeLabel}s`}</h1><p className="max-w-3xl text-muted-foreground">Policy-linked Course Offering assessment configuration with exact Faculty Allocation and governed academic-period scheduling.</p><nav className="mt-4 flex flex-wrap gap-2"><Button asChild variant={mode==='SETUP'?'default':'outline'}><Link href={`/college/${college.id}/internal-assessment/setup`}>Setup</Link></Button><Button asChild variant={mode==='ASSIGNMENT'?'default':'outline'}><Link href={`/college/${college.id}/internal-assessment/assignments`}>Assignments</Link></Button><Button asChild variant={mode==='QUIZ'?'default':'outline'}><Link href={`/college/${college.id}/internal-assessment/quizzes`}>Quizzes</Link></Button><Button asChild variant={mode==='MID_SEMESTER'?'default':'outline'}><Link href={`/college/${college.id}/internal-assessment/mid-semesters`}>Mid Semester</Link></Button><Button asChild variant={mode==='PRACTICAL'?'default':'outline'}><Link href={`/college/${college.id}/internal-assessment/practicals`}>Practical</Link></Button><Button asChild variant="outline"><Link href={`/college/${college.id}/internal-assessment/marks`}>Marks Entry</Link></Button></nav></header>
  {mode==='SETUP'&&can.setup&&<Card><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="size-5"/>Add Assessment Component</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><div className="lg:col-span-2"><SearchableSelect value={componentForm.data.course_offering_id} onValueChange={value=>componentForm.setData('course_offering_id',value)} placeholder="Course Offering" searchPlaceholder="Search course offering…" options={offerings.map(o=>({value:String(o.id),label:`${o.curriculum_course_mapping.course.code} · ${o.curriculum_course_mapping.course.name} · ${o.batch.name} · ${o.curriculum_course_mapping.slot.term.name}`,searchText:`${o.curriculum_course_mapping.course.code} ${o.curriculum_course_mapping.course.name} ${o.batch.name} ${o.curriculum_course_mapping.slot.term.name}`}))}/></div><SearchableSelect value={componentForm.data.component_type} onValueChange={value=>componentForm.setData('component_type',value)} placeholder="Assessment type" searchPlaceholder="Search assessment type…" options={['ASSIGNMENT','QUIZ','MID_SEMESTER','PRACTICAL','OTHER'].map(x=>({value:x,label:x.replaceAll('_',' ')}))}/><Input placeholder="Component name" value={componentForm.data.name} onChange={e=>componentForm.setData('name',e.target.value)}/><Input type="number" min="0.01" step="0.01" placeholder="Maximum marks" value={componentForm.data.maximum_marks} onChange={e=>componentForm.setData('maximum_marks',e.target.value)}/><Input type="number" min="0.01" max="100" step="0.01" placeholder="Weightage %" value={componentForm.data.weightage_percent} onChange={e=>componentForm.setData('weightage_percent',e.target.value)}/><Input type="number" min="0" step="0.01" placeholder="Minimum pass marks (optional)" value={componentForm.data.minimum_pass_marks} onChange={e=>componentForm.setData('minimum_pass_marks',e.target.value)}/><Input type="number" min="1" placeholder="Display order" value={componentForm.data.display_order} onChange={e=>componentForm.setData('display_order',e.target.value)}/><Textarea className="md:col-span-2 lg:col-span-3" placeholder="Notes (optional)" value={componentForm.data.notes} onChange={e=>componentForm.setData('notes',e.target.value)}/><div className="flex items-end"><Button className="w-full" disabled={componentForm.processing} onClick={createComponent}>{componentForm.processing?<Spinner/>:<Plus/>}Create Draft</Button></div><Errors errors={componentForm.errors}/></CardContent></Card>}
  {mode!=='SETUP'&&canCreateActivity&&<Card><CardHeader><CardTitle className="flex items-center gap-2"><ClipboardList className="size-5"/>Create {modeLabel}</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><SearchableSelect value={activityForm.data.internal_assessment_component_id} onValueChange={value=>{activityForm.setData('internal_assessment_component_id',value);activityForm.setData('faculty_allocation_id','')}} placeholder={`Active ${modeLabel} component`} searchPlaceholder={`Search ${modeLabel.toLowerCase()} component…`} options={modeComponents.filter(c=>c.status==='ACTIVE').map(c=>({value:String(c.id),label:`${c.course_offering.curriculum_course_mapping.course.code} · ${c.name} · ${c.maximum_marks} marks`,searchText:`${c.course_offering.curriculum_course_mapping.course.code} ${c.course_offering.curriculum_course_mapping.course.name} ${c.name}`}))}/><SearchableSelect value={activityForm.data.faculty_allocation_id} onValueChange={value=>activityForm.setData('faculty_allocation_id',value)} placeholder="Faculty Allocation" searchPlaceholder="Search faculty allocation…" options={eligibleAllocations.map(a=>({value:String(a.id),label:`${a.faculty.name} · ${a.teaching_role}${a.section_id?' · Section':' · Batch'}`,searchText:`${a.faculty.name} ${a.faculty.email} ${a.teaching_role}`}))}/><Input placeholder={`${modeLabel} title`} value={activityForm.data.title} onChange={e=>activityForm.setData('title',e.target.value)}/><div><p className="mb-1 text-sm font-medium">Opens at</p><DateTimePicker id="assessment-opens" name="opens_at" value={activityForm.data.opens_at} onValueChange={v=>activityForm.setData('opens_at',v)}/></div><div><p className="mb-1 text-sm font-medium">{mode==='ASSIGNMENT'?'Due at':'Closes at'}</p><DateTimePicker id="assessment-closes" name="closes_at" value={activityForm.data.closes_at} onValueChange={v=>activityForm.setData('closes_at',v)}/></div>{['QUIZ','MID_SEMESTER','PRACTICAL'].includes(mode)&&<Input type="number" min="1" max="1440" placeholder={`${modeLabel} duration minutes`} value={activityForm.data.duration_minutes} onChange={e=>activityForm.setData('duration_minutes',e.target.value)}/>}<Textarea className="md:col-span-2" placeholder="Instructions" value={activityForm.data.instructions} onChange={e=>activityForm.setData('instructions',e.target.value)}/><div className="flex items-end"><Button className="w-full" disabled={activityForm.processing} onClick={createActivity}>{activityForm.processing?<Spinner/>:<Plus/>}Create Draft</Button></div><Errors errors={activityForm.errors}/></CardContent></Card>}
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><BookOpenCheck className="size-5"/>{mode==='SETUP'?'Configured Components':`${mode==='QUIZ'?'Quiz':'Assignment'} Activities`}</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead className="bg-muted/40 text-left"><tr>{(mode==='SETUP'?['Course / Component','Type','Marks','Weightage','Policy','Status','Action']:['Title / Course','Faculty','Window','Component','Status','Action']).map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody className="divide-y">{mode==='SETUP'?modeComponents.map(c=><tr key={c.id}><td className="p-3 font-medium">{c.course_offering.curriculum_course_mapping.course.code} · {c.course_offering.curriculum_course_mapping.course.name}<div className="text-xs text-muted-foreground">{c.name} · {c.course_offering.batch.name}</div></td><td className="p-3">{c.component_type.replace('_',' ')}</td><td className="p-3">{c.maximum_marks}{c.minimum_pass_marks?` · pass ${c.minimum_pass_marks}`:''}</td><td className="p-3">{c.weightage_percent}%</td><td className="p-3">{c.academic_policy.code} · v{c.academic_policy.version}</td><td className="p-3"><Badge variant={c.status==='ACTIVE'?'default':'secondary'}>{c.status}</Badge></td><td className="p-3">{can.setup&&c.status==='DRAFT'&&<Button size="sm" onClick={()=>status('components',c.id,'ACTIVE')}><CheckCircle2/>Activate</Button>}{can.setup&&c.status==='ACTIVE'&&<Button size="sm" variant="outline" onClick={()=>status('components',c.id,'INACTIVE')}><StopCircle/>Deactivate</Button>}</td></tr>):activities.map(a=><tr key={a.id}><td className="p-3 font-medium">{a.title}<div className="text-xs text-muted-foreground">{a.component.course_offering.curriculum_course_mapping.course.code} · {a.component.course_offering.curriculum_course_mapping.course.name}</div></td><td className="p-3">{a.faculty_allocation.faculty.name}</td><td className="p-3">{new Date(a.opens_at).toLocaleString()}<div className="text-xs text-muted-foreground">to {new Date(a.closes_at).toLocaleString()}</div></td><td className="p-3">{a.component.name} · {a.component.maximum_marks} marks{a.duration_minutes?` · ${a.duration_minutes} min`:''}</td><td className="p-3"><Badge variant={a.status==='PUBLISHED'?'default':'secondary'}>{a.status}</Badge></td><td className="p-3">{a.status==='DRAFT'&&<Button size="sm" onClick={()=>status('activities',a.id,'PUBLISHED')}><Send/>Publish</Button>}{a.status==='PUBLISHED'&&<Button size="sm" variant="outline" onClick={()=>status('activities',a.id,'CLOSED')}><StopCircle/>Close</Button>}</td></tr>)}{((mode==='SETUP'&&!modeComponents.length)||(mode!=='SETUP'&&!activities.length))&&<tr><td colSpan={6} className="p-12 text-center text-muted-foreground">No records yet. Complete the linked Course Offering, Academic Policy and Faculty Allocation prerequisites first.</td></tr>}</tbody></table></div></CardContent></Card>
 </div></>;
}
function Errors({errors}:{errors:Record<string,string>}){
const values=Object.values(errors);

return values.length?<div className="md:col-span-2 lg:col-span-4">{values.map((e,i)=><p key={i} className="text-sm text-destructive">{e}</p>)}</div>:null;
}
