<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('college_payment_gateways',function(Blueprint $t){$t->id();$t->foreignId('university_id')->constrained('universities')->cascadeOnDelete();$t->foreignId('college_id')->constrained('colleges')->cascadeOnDelete();$t->string('provider',30);$t->string('display_name',100);$t->string('environment',20)->default('TEST');$t->string('merchant_id',150)->nullable();$t->string('key_id',255)->nullable();$t->text('key_secret')->nullable();$t->text('webhook_secret')->nullable();$t->string('status',20)->default('INACTIVE');$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['college_id','provider'],'cpg_college_provider_uq');});
  Schema::create('fee_head_gateway_mappings',function(Blueprint $t){$t->id();$t->foreignId('college_payment_gateway_id')->constrained('college_payment_gateways')->cascadeOnDelete();$t->foreignId('fee_head_id')->constrained('fee_heads')->restrictOnDelete();$t->string('product_code',120);$t->string('settlement_code',120)->nullable();$t->string('status',20)->default('ACTIVE');$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['college_payment_gateway_id','fee_head_id'],'fhgm_gateway_head_uq');$t->index(['fee_head_id','status'],'fhgm_head_status_idx');});
  $now=now(); foreach([['college_payment_gateway.view','view','View payment gateway configuration and fee-head mappings'],['college_payment_gateway.manage','manage','Manage payment gateway configuration and fee-head mappings']] as [$code,$action,$description]){DB::table('permissions')->updateOrInsert(['code'=>$code],['module'=>'Fee Management','resource'=>'college_payment_gateway','action'=>$action,'description'=>$description,'is_sensitive'=>$action!=='view','is_college_delegable'=>true,'status'=>'ACTIVE','created_at'=>$now,'updated_at'=>$now]);$pid=DB::table('permissions')->where('code',$code)->value('id');foreach(['SUPER_ADMIN','COLLEGE_ADMIN'] as $rc){$rid=DB::table('roles')->where('code',$rc)->where('status','ACTIVE')->value('id');if($rid&&$pid)DB::table('role_permissions')->updateOrInsert(['role_id'=>$rid,'permission_id'=>$pid],['created_at'=>$now,'updated_at'=>$now]);}}
 }
 public function down(): void {foreach(['college_payment_gateway.view','college_payment_gateway.manage'] as $c){$id=DB::table('permissions')->where('code',$c)->value('id');if($id)DB::table('role_permissions')->where('permission_id',$id)->delete();DB::table('permissions')->where('code',$c)->delete();}Schema::dropIfExists('fee_head_gateway_mappings');Schema::dropIfExists('college_payment_gateways');}
};
