<?php
namespace App\Http\Controllers;
use App\Http\Requests\{StoreCollegeAdmissionInterviewPanelRequest,UpsertCollegeAdmissionInterviewRequest};
use App\Models\{College,CollegeAdmissionApplicationChoice,CollegeAdmissionInterviewPanel,User};
use App\Services\{CollegeAdmissionInterviewPanelService,CollegeAdmissionInterviewService,CollegeAdmissionScoreService,CollegeReservationService};
use Illuminate\Http\{RedirectResponse,Request};
use Inertia\{Inertia,Response};
class CollegeAdmissionInterviewController extends Controller {
 public function index(Request $request,College $college,CollegeReservationService $reservationService):Response{
  $this->authorizeCollege($request,$college,'college_admission_interview.view');$search=trim((string)$request->query('search',''));
  $base=CollegeAdmissionApplicationChoice::query()->with(['application.admissionCycle.programOffering.programTemplate:id,name,code','intake.allocations.discipline:id,name,code','intake.allocations.specialization:id,name,code','selectionRule:id,name,code,version_no,interview_weight_percent,minimum_interview_score,minimum_final_score,merit_weight_percent,entrance_weight_percent','score','interview.evaluators','interview.panel'])->where('eligibility_status','ELIGIBLE')->whereHas('application',fn($q)=>$q->where('college_id',$college->id)->where('status','SUBMITTED'))->whereHas('selectionRule',fn($q)=>$q->where('interview_weight_percent','>',0))->whereHas('score');
  $choices=(clone $base)->when($search!=='',fn($q)=>$q->whereHas('application',fn($a)=>$a->where(fn($w)=>$w->where('application_no','like',"%{$search}%")->orWhere('candidate_name','like',"%{$search}%")->orWhere('email','like',"%{$search}%")->orWhere('phone','like',"%{$search}%"))))->orderByDesc('id')->paginate(25)->withQueryString();
  $choices->getCollection()->each(function($choice)use($reservationService){$bucket=$reservationService->availableBuckets($choice->intake)->firstWhere('bucket_key',$choice->bucket_key);$choice->setAttribute('bucket_label',$bucket['label']??$choice->bucket_key);});
  $schedulable=(clone $base)->whereDoesntHave('interview')->orderBy('id')->limit(500)->get()->map(fn($c)=>['id'=>$c->id,'application_no'=>$c->application->application_no,'candidate_name'=>$c->application->candidate_name,'preference_no'=>$c->preference_no,'program'=>$c->application->admissionCycle->programOffering->programTemplate->name,'rule_code'=>$c->selectionRule->code,'rule_version'=>$c->selectionRule->version_no]);
  $evaluators=User::query()->where('primary_college_id',$college->id)->where('account_type','COLLEGE_STAFF')->where('status','ACTIVE')->whereHas('roles',fn($q)=>$q->where('roles.status','ACTIVE')->where('user_roles.status','ACTIVE')->where('user_roles.scope_type','COLLEGE')->where('user_roles.scope_reference',"college:{$college->id}")->where(fn($r)=>$r->whereNull('user_roles.effective_from')->orWhere('user_roles.effective_from','<=',now()))->where(fn($r)=>$r->whereNull('user_roles.effective_until')->orWhere('user_roles.effective_until','>=',now()))->where(fn($eligible)=>$eligible->where('roles.code','COLLEGE_ADMIN')->orWhereHas('permissions',fn($p)=>$p->where('permissions.code','college_admission_interview.evaluate')->where('permissions.status','ACTIVE'))))->with(['roles'=>fn($q)=>$q->select('roles.id','roles.name','roles.code')->where('roles.status','ACTIVE')->wherePivot('status','ACTIVE')->wherePivot('scope_type','COLLEGE')->wherePivot('scope_reference',"college:{$college->id}")->where(fn($r)=>$r->whereNull('user_roles.effective_from')->orWhere('user_roles.effective_from','<=',now()))->where(fn($r)=>$r->whereNull('user_roles.effective_until')->orWhere('user_roles.effective_until','>=',now()))->where(fn($eligible)=>$eligible->where('roles.code','COLLEGE_ADMIN')->orWhereHas('permissions',fn($p)=>$p->where('permissions.code','college_admission_interview.evaluate')->where('permissions.status','ACTIVE')))])->orderBy('name')->get(['id','name','email','account_type','primary_college_id']);
  $panels=CollegeAdmissionInterviewPanel::query()->where('college_id',$college->id)->withCount('interviews')->with(['evaluators:id,college_admission_interview_panel_id,evaluator_name_snapshot','breakPeriods'])->orderByDesc('starts_at')->limit(20)->get();
  return Inertia::render('college-admission-interviews/index',['college'=>$college->only(['id','name','code','status']),'choices'=>$choices,'schedulableChoices'=>$schedulable,'evaluators'=>$evaluators,'panels'=>$panels,'filters'=>['search'=>$search],'can'=>['manage'=>$request->user()->hasCollegePermission('college_admission_interview.manage',$college->id)]]);
 }
 public function storePanel(StoreCollegeAdmissionInterviewPanelRequest $request,College $college,CollegeAdmissionInterviewPanelService $service):RedirectResponse{$this->authorizeCollege($request,$college,'college_admission_interview.manage');$panel=$service->createAndAssign($college,$request->validated(),$request->user()->id,$request->ip());return back()->with('toast',['type'=>'success','message'=>"Panel {$panel->name} created and {$panel->interviews->count()} candidate interview slot(s) scheduled. Emails were attempted using the central mail configuration."]);}
 public function upsert(UpsertCollegeAdmissionInterviewRequest $request,College $college,CollegeAdmissionApplicationChoice $choice,CollegeAdmissionInterviewService $service,CollegeAdmissionScoreService $scoreService):RedirectResponse{$this->authorizeCollege($request,$college,'college_admission_interview.manage');$service->save($college,$choice,$request->validated(),$request->user()->id,$request->ip(),$scoreService);return back()->with('toast',['type'=>'success','message'=>'Interview schedule / evaluation saved and Admission score re-evaluated.']);}
 private function authorizeCollege(Request $request,College $college,string $permission):void{abort_unless($request->user()->hasCollegePermission($permission,$college->id),403);}
}
