import { Form, Head, router } from '@inertiajs/react';
import { CheckCircle2, ChevronDown, Download, FileSpreadsheet, GripVertical, Plug, RotateCcw, Save, Upload, UserRoundPlus, X, XCircle } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useAppDialog } from '@/components/app-dialog-provider';
import { useAppLoading } from '@/components/app-loading-provider';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Spinner } from '@/components/ui/spinner';

type Session={id:number;name:string;code:string;is_current:boolean}; type Offering={id:number;name:string|null;code:string|null};
type Target={key:string;label:string;required?:boolean;group?:string;profile_key?:string;field_type?:string;hint?:string;academic_choice?:boolean;mode?:string}; type PreviewRow={row:number;values:Record<string,string>;errors:string[]};
type Meta={session_id:number;offering_id:number;mapping:Record<string,string>;preview:PreviewRow[];total:number;valid:number;invalid:number;validated_at:string};
type ImportState={token:string;headers:string[];meta:Meta|null}|null;
type SavedMapping={id:number;name:string;college_program_offering_id:number;mapping:Record<string,string>;updated_at:string};
type ImportContext={template_found:boolean|null;profile_field_count:number;required_profile_field_count:number;curriculum_found:boolean|null};
type Props={college:{id:number;name:string;code:string};sessions:Session[];offerings:Offering[];session_id:number;offering_id:number;targets:Target[];importState:ImportState;savedMappings:SavedMapping[];importContext:ImportContext;can:{manage:boolean}};

export default function Index({college,sessions,offerings,session_id,offering_id,targets,importState,savedMappings,importContext,can}:Props){
 const [sessionId,setSessionId]=useState(String(importState?.meta?.session_id||session_id||''));
 const [offeringId,setOfferingId]=useState(importState?.meta?.offering_id?String(importState.meta.offering_id):String(offering_id||''));
 const suggested=useMemo(()=>{const m:Record<string,string>={}; if(importState) targets.forEach(t=>{const h=importState.headers.find(x=>x.toLowerCase()===t.key.toLowerCase());if(h)m[t.key]=h}); return {...m,...(importState?.meta?.mapping||{})};},[importState,targets]);
 const [mapping,setMapping]=useState<Record<string,string>>(suggested); const [dragHeader,setDragHeader]=useState(''); const [mappingName,setMappingName]=useState(''); const [openGroup,setOpenGroup]=useState('Core Student');
 useEffect(()=>setMapping(suggested),[suggested]); const {isLoading:loading,setNextLoadingLabel}=useAppLoading(); const dialog=useAppDialog();
 const changeSession=(v:string)=>{setSessionId(v);setOfferingId('');setNextLoadingLabel('Loading programme offerings…');router.get(`/college/${college.id}/student-imports`,{session_id:v,token:importState?.token},{preserveState:false,preserveScroll:true});};
 const changeOffering=(v:string)=>{setOfferingId(v);setNextLoadingLabel('Loading Student Profile fields…');router.get(`/college/${college.id}/student-imports`,{session_id:sessionId,offering_id:v,token:importState?.token},{preserveState:false,preserveScroll:true});};
 const usedHeaders=useMemo(()=>new Set(Object.values(mapping).filter(Boolean)),[mapping]);
 const missingRequired=useMemo(()=>targets.filter(t=>t.required&&!mapping[t.key]),[targets,mapping]);
 const assign=(target:string,header:string)=>setMapping(prev=>{const next={...prev};Object.keys(next).forEach(k=>{if(next[k]===header)next[k]=''});next[target]=header;return next;});
 const loadSaved=(m:SavedMapping)=>{const next:Record<string,string>={};Object.entries(m.mapping||{}).forEach(([k,h])=>{if(targets.some(t=>t.key===k)&&importState?.headers.includes(h))next[k]=h});setMapping(next);setMappingName(m.name);};
 const saveMapping=()=>{if(!offeringId||!mapping.full_name)return;const name=mappingName.trim()||`${offerings.find(o=>String(o.id)===offeringId)?.code||'Student'} Import Mapping`;router.post(`/college/${college.id}/student-imports/mappings`,{session_id:sessionId,offering_id:offeringId,name,mapping},{preserveScroll:true});};
 const doImport=async()=>{if(!importState?.meta||importState.meta.invalid>0||loading)return;const ok=await dialog.confirm({title:'Import validated students?',description:`Create ${importState.meta.valid} Student and Enrollment record(s) in the selected Programme Offering?\n\nRows with blank institutional identities will remain Pending in Student Identity. This import does not create Admissions or Fee records.`,confirmLabel:'Import Students',confirmIcon:<UserRoundPlus className="size-4"/>});if(!ok)return;setNextLoadingLabel('Importing students…');router.post(`/college/${college.id}/student-imports/import`,{token:importState.token},{preserveScroll:true});};
 return <><Head title="Student Import / Migration"/><div className="space-y-5 p-4 md:p-6">
  <div className="flex items-start gap-3"><div className="mt-0.5 rounded-lg border bg-card p-2"><FileSpreadsheet className="size-5"/></div><div><h1 className="text-xl font-semibold">Student Import / Migration</h1><p className="text-sm text-muted-foreground">Migrate existing students through CSV validation into the same authoritative Student and Enrollment architecture.</p></div></div>
  <Card><CardHeader><CardTitle>1. Download Template & Upload CSV</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2"><Button variant="outline" asChild><a href={`/college/${college.id}/student-imports/template`}><Download className="size-4"/>Download CSV Template</a></Button></div>{can.manage&&<Form action={`/college/${college.id}/student-imports/upload`} method="post" encType="multipart/form-data">{({processing,errors})=><div className="flex flex-wrap items-end gap-3"><div className="min-w-[280px] flex-1"><Label htmlFor="student-import-file">CSV File</Label><input id="student-import-file" name="file" type="file" accept=".csv,text/csv" className="mt-2 block w-full rounded-md border bg-background px-3 py-2 text-sm" required disabled={processing||loading}/>{errors.file&&<p className="mt-1 text-xs text-destructive">{errors.file}</p>}</div><Button type="submit" disabled={processing||loading}>{processing?<Spinner/>:<Upload className="size-4"/>}Upload CSV</Button></div>}</Form>}<p className="text-xs text-muted-foreground">Maximum 5 MB. The template supports existing Student UID / University Roll / Class Roll values for legacy migration. Leave them blank to assign later from Student Identity.</p></CardContent></Card>
  {importState&&<Card><CardHeader><CardTitle>2. Connect CSV Columns to Student Fields</CardTitle></CardHeader><CardContent className="space-y-5"><div className="grid gap-3 md:grid-cols-2"><div><Label>Session</Label><Select value={sessionId} onValueChange={changeSession} disabled={loading}><SelectTrigger className="mt-2"><SelectValue placeholder="Select Session"/></SelectTrigger><SelectContent>{sessions.map(s=><SelectItem key={s.id} value={String(s.id)}>{s.name}{s.is_current?' · Current':''}</SelectItem>)}</SelectContent></Select></div><div><Label>Programme Offering</Label><Select value={offeringId} onValueChange={changeOffering} disabled={loading}><SelectTrigger className="mt-2"><SelectValue placeholder="Select Programme Offering"/></SelectTrigger><SelectContent>{offerings.map(o=><SelectItem key={o.id} value={String(o.id)}>{o.name}{o.code?` (${o.code})`:''}</SelectItem>)}</SelectContent></Select></div></div>
   {offeringId&&importContext.template_found===false&&<div className="rounded-xl border border-amber-300/60 bg-amber-50/50 p-3 text-sm dark:bg-amber-950/10"><div className="font-medium">No applicable Admission Form Template found for this Programme Offering.</div><div className="mt-1 text-muted-foreground">Import remains available with Core Student fields and Curriculum Academic Context. No template-based Student Profile fields will be collected or required.</div></div>}
   {offeringId&&importContext.template_found===true&&<div className="rounded-xl border bg-muted/20 p-3 text-sm"><span className="font-medium">Admission Form profile rules active.</span> {importContext.profile_field_count} Student Profile field(s) apply; {importContext.required_profile_field_count} are required for every imported student.</div>}
   {savedMappings.length>0&&<div className="rounded-xl border bg-muted/20 p-3"><div className="mb-2 flex items-center gap-2 text-sm font-medium"><Save className="size-4"/>Saved mappings for this Programme Offering</div><div className="flex flex-wrap gap-2">{savedMappings.map(m=><div key={m.id} className="flex items-center overflow-hidden rounded-lg border bg-background"><button type="button" className="px-3 py-2 text-sm hover:bg-muted" onClick={()=>loadSaved(m)}>{m.name}</button><a className="border-l px-2 py-2 hover:bg-muted" title="Download this mapping as CSV template" href={`/college/${college.id}/student-imports/mappings/${m.id}/template`}><Download className="size-4"/></a></div>)}</div></div>}
   {can.manage&&<Form action={`/college/${college.id}/student-imports/preview`} method="post">{({processing,errors})=><div className="space-y-5"><input type="hidden" name="token" value={importState.token}/><input type="hidden" name="session_id" value={sessionId}/><input type="hidden" name="offering_id" value={offeringId}/>{Object.entries(mapping).map(([k,v])=><input key={k} type="hidden" name={`mapping[${k}]`} value={v||''}/>)}
    <div className="grid gap-4 xl:grid-cols-[minmax(240px,.75fr)_minmax(440px,1.5fr)_minmax(250px,.75fr)]">
     <div className="rounded-xl border bg-card p-3"><div className="mb-3 flex items-center justify-between"><div><div className="font-semibold">CSV Columns</div><div className="text-xs text-muted-foreground">Drag a column by its plug.</div></div><Badge variant="secondary">{importState.headers.length}</Badge></div><div className="max-h-[620px] space-y-2 overflow-auto pr-1">{importState.headers.map(h=>{const used=usedHeaders.has(h);return <div key={h} draggable={!used} onDragStart={()=>setDragHeader(h)} onDragEnd={()=>setDragHeader('')} className={`flex items-center gap-2 rounded-lg border px-3 py-2 text-sm transition ${used?'bg-primary/5 text-muted-foreground':'cursor-grab bg-background hover:border-primary/50 hover:shadow-sm'}`}><GripVertical className="size-4 shrink-0 opacity-50"/><span className="min-w-0 flex-1 truncate">{h}</span><Plug className={`size-4 shrink-0 ${used?'text-primary':'text-muted-foreground'}`}/>{used&&<CheckCircle2 className="size-4 shrink-0 text-primary"/>}</div>})}</div></div>
     <div className="rounded-xl border bg-card p-3"><div className="mb-3 flex items-center justify-between"><div><div className="font-semibold">Student Fields</div><div className="text-xs text-muted-foreground">Drop the matching CSV plug onto a field socket. Each CSV column connects once.</div></div><Button type="button" variant="ghost" size="sm" onClick={()=>setMapping({})}><RotateCcw className="size-4"/>Clear</Button></div>{['Core Student','Student Identity','Academic Context','Student Profile'].map(group=>{const items=targets.filter(t=>t.group===group);if(!items.length)return null;const open=openGroup===group;const mapped=items.filter(t=>Boolean(mapping[t.key])).length;return <div key={group} className="mb-3 overflow-hidden rounded-lg border"><button type="button" onClick={()=>setOpenGroup(open?'':group)} className="flex w-full items-center gap-2 bg-muted/40 px-3 py-2.5 text-left text-sm font-semibold hover:bg-muted/60"><span className="flex-1">{group==='Student Profile'?'Student Profile Fields (from Admission Form)':group==='Academic Context'?'Academic Context (from Programme Offering Curriculum)':group+' Fields'}</span><Badge variant="secondary">{mapped}/{items.length}</Badge><ChevronDown className={`size-4 transition-transform ${open?'rotate-180':''}`}/></button>{open&&<div className="grid gap-2 p-3 md:grid-cols-2">{items.map(t=>{const h=mapping[t.key]||'';return <div key={t.key} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(dragHeader)assign(t.key,dragHeader);setDragHeader('')}} className={`group rounded-lg border p-2 transition ${dragHeader?'border-dashed border-primary/50 bg-primary/5':''}`}><div className="mb-1 flex items-center gap-2"><Plug className={`size-4 ${h?'text-primary':'text-muted-foreground'}`}/><Label className="min-w-0 flex-1">{t.label}{t.required&&<span className="text-destructive"> *</span>}{t.hint&&<span className="mt-0.5 block text-[11px] font-normal text-muted-foreground">{t.hint}</span>}</Label></div>{h?<div className="flex items-center gap-2 rounded-md bg-primary/10 px-2.5 py-2 text-sm"><Plug className="size-4 text-primary"/><span className="min-w-0 flex-1 truncate font-medium">{h}</span><button type="button" onClick={()=>setMapping(x=>({...x,[t.key]:''}))} className="rounded p-0.5 hover:bg-background" aria-label={`Disconnect ${h}`}><X className="size-4"/></button></div>:<div className="flex min-h-9 items-center justify-center gap-2 rounded-md border border-dashed px-2 text-xs text-muted-foreground"><Plug className="size-4"/>Drop CSV plug here</div>}</div>})}</div>}</div>})}</div>
     <div className="space-y-3"><div className="rounded-xl border bg-primary/5 p-4"><div className="flex items-center gap-2 font-semibold"><Plug className="size-5 text-primary"/>Drag & Plug</div><p className="mt-2 text-sm text-muted-foreground">Connect CSV columns on the left to Student fields. Used columns are automatically locked so duplicate mapping cannot happen.</p></div><div className="rounded-xl border p-4"><div className="font-semibold">Required mapping check</div>{missingRequired.length?<><p className="mt-1 text-xs text-destructive">Connect all required fields before validation.</p><div className="mt-2 space-y-1">{missingRequired.map(t=><div key={t.key} className="text-xs text-destructive">• {t.label}</div>)}</div></>:<p className="mt-1 text-xs text-muted-foreground">All required fields are connected.</p>}</div><div className="rounded-xl border p-4"><div className="font-semibold">Save this mapping</div><p className="mt-1 text-xs text-muted-foreground">Reuse it for future batches of this Programme Offering and download a ready-to-use template.</p><Input className="mt-3" value={mappingName} onChange={e=>setMappingName(e.target.value)} placeholder="e.g. BA Legacy Import"/><Button type="button" variant="outline" className="mt-2 w-full" onClick={saveMapping} disabled={!offeringId||!mapping.full_name}><Save className="size-4"/>Save Mapping</Button></div><div className="rounded-xl border p-4"><div className="font-semibold">Connection status</div><div className="mt-2 text-sm"><span className="font-semibold text-primary">{usedHeaders.size}</span> columns connected</div><div className="text-xs text-muted-foreground">{targets.length-Object.values(mapping).filter(Boolean).length} Student fields not mapped</div></div></div>
    </div>{Object.values(errors).filter(Boolean).map((e,i)=><p key={i} className="text-sm text-destructive">{String(e)}</p>)}<div className="flex justify-end"><Button type="submit" disabled={processing||loading||!offeringId||!mapping.full_name||missingRequired.length>0}>{processing?<Spinner/>:<CheckCircle2 className="size-4"/>}Validate & Preview</Button></div></div>}</Form>}
  </CardContent></Card>}
  {importState?.meta&&<Card><CardHeader><CardTitle>3. Validation Preview</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2"><Badge variant="secondary">Total {importState.meta.total}</Badge><Badge variant="secondary"><CheckCircle2 className="mr-1 size-3"/>Valid {importState.meta.valid}</Badge><Badge variant={importState.meta.invalid?'destructive':'secondary'}>{importState.meta.invalid?<XCircle className="mr-1 size-3"/>:<CheckCircle2 className="mr-1 size-3"/>}Invalid {importState.meta.invalid}</Badge></div><div className="overflow-x-auto rounded-md border"><table className="w-full min-w-[1000px] text-sm"><thead className="border-b bg-muted/30"><tr><th className="px-3 py-2 text-left">CSV Row</th><th className="px-3 py-2 text-left">Student</th><th className="px-3 py-2 text-left">DOB</th><th className="px-3 py-2 text-left">Email / Phone</th><th className="px-3 py-2 text-left">Student UID</th><th className="px-3 py-2 text-left">University Roll</th><th className="px-3 py-2 text-left">Class Roll</th><th className="px-3 py-2 text-left">Discipline</th><th className="px-3 py-2 text-left">Validation</th></tr></thead><tbody>{importState.meta.preview.map(r=><tr key={r.row} className="border-b last:border-0"><td className="px-3 py-3">{r.row}</td><td className="px-3 py-3 font-medium">{r.values.full_name||'—'}</td><td className="px-3 py-3">{r.values.date_of_birth||'—'}</td><td className="px-3 py-3">{r.values.email||'—'}<div className="text-xs text-muted-foreground">{r.values.phone||''}</div></td><td className="px-3 py-3 font-mono">{r.values.student_uid||'Pending'}</td><td className="px-3 py-3 font-mono">{r.values.university_roll_no||'Pending'}</td><td className="px-3 py-3 font-mono">{r.values.class_roll_no||'Pending'}</td><td className="px-3 py-3">{r.values.discipline_code||'—'}</td><td className="px-3 py-3">{r.errors.length?<div className="space-y-1">{r.errors.map((e,i)=><div key={i} className="text-xs text-destructive">{e}</div>)}</div>:<Badge variant="secondary"><CheckCircle2 className="mr-1 size-3"/>Valid</Badge>}</td></tr>)}</tbody></table></div>{importState.meta.total>importState.meta.preview.length&&<p className="text-xs text-muted-foreground">Showing the first {importState.meta.preview.length} rows. All {importState.meta.total} rows were validated server-side.</p>}{can.manage&&<Button onClick={doImport} disabled={loading||importState.meta.invalid>0||importState.meta.valid===0}><UserRoundPlus className="size-4"/>Import {importState.meta.valid} Students</Button>}{importState.meta.invalid>0&&<p className="text-sm text-destructive">Import is blocked until every row is valid. Correct the CSV and upload it again.</p>}</CardContent></Card>}
 </div></>;
}
