import { Form, Head, router } from '@inertiajs/react';
import { Calculator, Search } from 'lucide-react';
import { Spinner } from '@/components/ui/spinner';
import { FormEvent, useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';

type Rule={id:number;name:string;code:string;version_no:number;selection_mode:string;merit_weight_percent:string;entrance_weight_percent:string;interview_weight_percent:string;minimum_merit_score:string|null;minimum_entrance_score:string|null;minimum_interview_score:string|null;minimum_final_score:string|null};
type Score={id:number;merit_raw_score:string|null;merit_max_score:string|null;merit_normalized_score:string|null;entrance_raw_score:string|null;entrance_max_score:string|null;entrance_normalized_score:string|null;interview_normalized_score:string|null;final_weighted_score:string|null;qualification_status:string;qualification_reason:string|null;notes:string|null};
type Choice={id:number;preference_no:number;bucket_label:string;eligibility_status:string;application:{id:number;application_no:string;candidate_name:string;email:string|null;phone:string|null;admission_cycle:{name:string;program_offering:{program_template:{name:string;code:string};academic_session:{name:string;code:string}}}};selection_rule:Rule;score:Score|null};
type Props={college:{id:number;name:string;code:string;status:string};choices:{data:Choice[];current_page:number;last_page:number;total:number;prev_page_url:string|null;next_page_url:string|null};filters:{search:string};can:{manage:boolean}};

const n=(v:string|null|undefined)=>v==null?'—':Number(v).toFixed(3);
const pct=(v:string)=>Number(v).toFixed(2)+'%';
function statusClass(s:string){if(s==='QUALIFIED')return 'border-emerald-200 bg-emerald-50 text-emerald-700';if(s==='NOT_QUALIFIED')return 'border-destructive/30 bg-destructive/5 text-destructive';return 'border-amber-200 bg-amber-50 text-amber-700';}

function ScoreDialog({collegeId,choice}:{collegeId:number;choice:Choice}){
 const r=choice.selection_rule,s=choice.score; const merit=Number(r.merit_weight_percent)>0, entrance=Number(r.entrance_weight_percent)>0, interview=Number(r.interview_weight_percent)>0;
 const [mr,setMr]=useState(s?.merit_raw_score??''),[mm,setMm]=useState(s?.merit_max_score??''),[er,setEr]=useState(s?.entrance_raw_score??''),[em,setEm]=useState(s?.entrance_max_score??'');
 const norm=(a:string,b:string)=>{const x=Number(a),y=Number(b);return a!==''&&b!==''&&y>0&&x>=0&&x<=y?((x/y)*100).toFixed(3):'—'};
 return <Dialog><DialogTrigger asChild><Button size="sm" variant="outline"><Calculator/>{s?'Edit Scores':'Capture Scores'}</Button></DialogTrigger><DialogContent className="w-[calc(100vw-2rem)] sm:!max-w-3xl max-h-[92vh] overflow-hidden"><DialogHeader><DialogTitle>{s?'Edit':'Capture'} Score / Normalization</DialogTitle><DialogDescription>Raw scores are normalized to 0–100 by the backend and evaluated against locked {r.code} V{r.version_no}. Interview score is owned by the later Interview Scheduling / Evaluation module.</DialogDescription></DialogHeader><Form action={`/college/${collegeId}/admission-application-choices/${choice.id}/scores`} method="put">{({processing,errors})=><><div className="max-h-[68vh] space-y-4 overflow-y-auto pr-1"><div className="rounded-md border bg-muted/20 p-3 text-sm"><div className="font-medium">{choice.application.candidate_name} · {choice.application.application_no}</div><div className="text-muted-foreground">Preference {choice.preference_no} · {choice.bucket_label}</div><div className="mt-1 text-xs text-muted-foreground">Rule {r.code} V{r.version_no} · Merit {pct(r.merit_weight_percent)} · Entrance {pct(r.entrance_weight_percent)} · Interview {pct(r.interview_weight_percent)}</div></div>{Object.values(errors).filter(Boolean).map((e,i)=><div key={i} className="rounded-md border border-destructive/40 bg-destructive/5 px-3 py-2 text-sm text-destructive">{String(e)}</div>)}
 {merit&&<div className="rounded-md border p-3"><div className="font-medium">Merit / Qualifying Component</div><p className="text-xs text-muted-foreground">Minimum: {r.minimum_merit_score??'Not set'} / 100</p><div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="space-y-1 text-sm"><span>Raw Score</span><Input name="merit_raw_score" type="number" step="0.001" min="0" value={mr} onChange={e=>setMr(e.target.value)} required/></label><label className="space-y-1 text-sm"><span>Maximum Score</span><Input name="merit_max_score" type="number" step="0.001" min="0.001" value={mm} onChange={e=>setMm(e.target.value)} required/></label><div className="rounded-md border bg-muted/30 p-3 text-sm"><div className="text-xs text-muted-foreground">Normalized preview</div><div className="mt-1 font-semibold">{norm(mr,mm)} / 100</div></div></div></div>}
 {entrance&&<div className="rounded-md border p-3"><div className="font-medium">Entrance Component</div><p className="text-xs text-muted-foreground">Minimum: {r.minimum_entrance_score??'Not set'} / 100</p><div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="space-y-1 text-sm"><span>Raw Score</span><Input name="entrance_raw_score" type="number" step="0.001" min="0" value={er} onChange={e=>setEr(e.target.value)} required/></label><label className="space-y-1 text-sm"><span>Maximum Score</span><Input name="entrance_max_score" type="number" step="0.001" min="0.001" value={em} onChange={e=>setEm(e.target.value)} required/></label><div className="rounded-md border bg-muted/30 p-3 text-sm"><div className="text-xs text-muted-foreground">Normalized preview</div><div className="mt-1 font-semibold">{norm(er,em)} / 100</div></div></div></div>}
 {interview&&<div className="rounded-md border border-dashed p-3"><div className="font-medium">Interview Component · {pct(r.interview_weight_percent)}</div><p className="mt-1 text-sm text-muted-foreground">Not entered here. The future Interview Scheduling / Evaluation module will write the normalized interview score and trigger final re-evaluation.</p><p className="mt-1 text-xs text-muted-foreground">Minimum interview score: {r.minimum_interview_score??'Not set'} / 100</p></div>}
 <label className="block space-y-1 text-sm"><span>Notes (optional)</span><textarea name="notes" defaultValue={s?.notes??''} className="min-h-24 w-full rounded-md border bg-background px-3 py-2"/></label></div><DialogFooter><DialogClose asChild><Button type="button" variant="outline">Cancel</Button></DialogClose><Button type="submit" disabled={processing}>{processing&&<Spinner/>}Normalize & Save</Button></DialogFooter></>}</Form></DialogContent></Dialog>;
}

export default function AdmissionScores({college,choices,filters,can}:Props){
 const [search,setSearch]=useState(filters.search??'');
 const submit=(e:FormEvent)=>{e.preventDefault();router.get(`/college/${college.id}/admission-scores`,search.trim()?{search:search.trim()}:{},{preserveState:true,replace:true});};
 return <><Head title="Score Capture / Normalization"/><div className="space-y-6 p-4 md:p-6"><header className="border-b pb-5"><p className="text-sm font-medium text-primary">{college.code} · Student Admission Processing</p><h1 className="text-3xl font-semibold">Score Capture / Normalization</h1><p className="max-w-4xl text-sm text-muted-foreground">Capture only the score components required by each SUBMITTED + ELIGIBLE choice's locked Selection Rule. Raw marks are normalized to 0–100 for deterministic Merit / Interview / Roster processing.</p></header><Card><CardContent className="p-4"><form onSubmit={submit} className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} className="pl-9" placeholder="Search application no, candidate, email or phone"/></div><Button type="submit" variant="outline"><Search/>Search</Button></form></CardContent></Card>
 {choices.data.length===0?<Card><CardContent className="grid place-items-center py-16 text-center"><Calculator className="size-10 text-muted-foreground"/><h2 className="mt-3 font-semibold">No eligible submitted choice is ready</h2><p className="mt-1 text-sm text-muted-foreground">Submit an Admission Application and mark its preference ELIGIBLE first.</p></CardContent></Card>:<div className="space-y-4">{choices.data.map(c=>{const s=c.score,r=c.selection_rule;return <Card key={c.id}><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle>{c.application.candidate_name}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{c.application.application_no} · {c.application.admission_cycle.program_offering.program_template.name} · {c.application.admission_cycle.program_offering.academic_session.name}</p><p className="mt-1 text-sm text-muted-foreground">Preference {c.preference_no} · {c.bucket_label}</p></div>{can.manage&&<ScoreDialog collegeId={college.id} choice={c}/>}</div></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div><div className="text-xs text-muted-foreground">Locked Rule</div><div className="font-medium">{r.code} V{r.version_no}</div></div><div><div className="text-xs text-muted-foreground">Merit</div><div>{s?n(s.merit_normalized_score):'Not captured'}</div></div><div><div className="text-xs text-muted-foreground">Entrance</div><div>{s?n(s.entrance_normalized_score):'Not captured'}</div></div><div><div className="text-xs text-muted-foreground">Interview</div><div>{s?n(s.interview_normalized_score):Number(r.interview_weight_percent)>0?'Pending Interview':'Not required'}</div></div><div><div className="text-xs text-muted-foreground">Qualification</div>{s?<span className={`inline-block rounded-full border px-2 py-0.5 text-xs ${statusClass(s.qualification_status)}`}>{s.qualification_status.replaceAll('_',' ')}</span>:<span className="text-muted-foreground">Not evaluated</span>}</div></div>{s?.final_weighted_score&&<p className="mt-3 text-sm"><span className="font-medium">Final weighted score:</span> {n(s.final_weighted_score)} / 100</p>}{s?.qualification_reason&&<p className="mt-2 text-sm text-muted-foreground">{s.qualification_reason}</p>}</CardContent></Card>})}</div>}</div></>;
}
