import { Form, Head, router } from '@inertiajs/react';
import { BadgeCheck, ChevronLeft, ChevronRight, Fingerprint, Search, Settings2, TicketCheck } from 'lucide-react';
import { useState } from 'react';
import { useAppDialog } from '@/components/app-dialog-provider';
import { useAppLoading } from '@/components/app-loading-provider';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Spinner } from '@/components/ui/spinner';

type Session={id:number;name:string;code:string;is_current:boolean}; type Offering={id:number;name:string|null;code:string|null}; type Discipline={id:number;name:string;code:string|null};
type Row={id:number;student_id:number;name:string|null;student_uid:string|null;university_roll_no:string|null;class_roll_no:string|null;programme:string|null;discipline:string|null;discipline_code:string|null;session:string|null;complete:boolean};
type Page<T>={data:T[];current_page:number;last_page:number;from:number|null;to:number|null;total:number;prev_page_url:string|null;next_page_url:string|null};
type Props={college:{id:number;name:string;code:string};sessions:Session[];offerings:Offering[];disciplines:Discipline[];students:Page<Row>;settings:{student_uid_format:string;university_roll_format:string;class_roll_format:string;class_roll_scope:'PROGRAMME_OFFERING'|'DISCIPLINE'};filters:{session_id:number;offering_id:number;discipline_id:number;q:string;per_page:number};can:{manage:boolean}};

export default function Index({college,sessions,offerings,disciplines,students,settings,filters,can}:Props){
 const [q,setQ]=useState(filters.q??''); const [sessionId,setSessionId]=useState(String(filters.session_id||'')); const [offeringId,setOfferingId]=useState(filters.offering_id?String(filters.offering_id):'all'); const [disciplineId,setDisciplineId]=useState(filters.discipline_id?String(filters.discipline_id):'all'); const [perPage,setPerPage]=useState(String(filters.per_page||25));
 const {isLoading:loading,setNextLoadingLabel}=useAppLoading(); const dialog=useAppDialog();
 const visit=(params:Record<string,string|number|null>={},label='Loading student identities…')=>{setNextLoadingLabel(label);router.get(`/college/${college.id}/student-identities`,{q,session_id:sessionId,offering_id:offeringId==='all'?null:offeringId,discipline_id:disciplineId==='all'?null:disciplineId,per_page:perPage,...params},{preserveState:true,preserveScroll:true});};
 const assign=async(r:Row)=>{if(r.complete||loading||!can.manage)return; const ok=await dialog.confirm({title:'Assign Student Identities',description:`Assign the configured Student UID, University Roll No. and Class Roll No. to ${r.name??'this student'}?\n\nAlready assigned identifiers will never be replaced.\nExam Roll No. is not assigned here.`,confirmLabel:'Assign Identities',confirmIcon:<Fingerprint className="size-4"/>}); if(!ok)return; setNextLoadingLabel('Assigning student identities…'); router.post(`/college/${college.id}/student-identities/${r.id}/assign`,{}, {preserveScroll:true});};
 const page=(url:string|null)=>{if(!url)return;setNextLoadingLabel('Loading student identities…');router.visit(url,{preserveState:true,preserveScroll:true});};
 return <><Head title="Student Identity"/><div className="space-y-5 p-4 md:p-6">
  <div className="flex items-start gap-3"><div className="mt-0.5 rounded-lg border bg-card p-2"><Fingerprint className="size-5"/></div><div><h1 className="text-xl font-semibold">Student Identity</h1><p className="text-sm text-muted-foreground">Configure and assign permanent Student UID, University Roll No. and enrollment-specific Class Roll No. Exam Roll remains owned by Examination.</p></div></div>
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><Settings2 className="size-4"/>Identity Numbering Rules</CardTitle></CardHeader><CardContent><Form action={`/college/${college.id}/student-identities/settings`} method="patch">{({processing,errors})=><div className="space-y-4"><div className="grid gap-4 lg:grid-cols-4">
   <div><Label>Student UID Format</Label><Input name="student_uid_format" className="mt-2 font-mono" defaultValue={settings.student_uid_format} disabled={!can.manage}/><p className="mt-1 text-xs text-destructive">{errors.student_uid_format}</p></div>
   <div><Label>University Roll No. Format</Label><Input name="university_roll_format" className="mt-2 font-mono" defaultValue={settings.university_roll_format} disabled={!can.manage}/><p className="mt-1 text-xs text-destructive">{errors.university_roll_format}</p></div>
   <div><Label>Class Roll No. Format</Label><Input name="class_roll_format" className="mt-2 font-mono" defaultValue={settings.class_roll_format} disabled={!can.manage}/><p className="mt-1 text-xs text-destructive">{errors.class_roll_format}</p></div>
   <div><Label>Class Roll Scope</Label><Select name="class_roll_scope" defaultValue={settings.class_roll_scope??'PROGRAMME_OFFERING'} disabled={!can.manage||processing}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="PROGRAMME_OFFERING">Programme Offering</SelectItem><SelectItem value="DISCIPLINE">Discipline</SelectItem></SelectContent></Select><p className="mt-1 text-xs text-destructive">{errors.class_roll_scope}</p></div>
  </div><p className="text-xs leading-5 text-muted-foreground">Supported tokens: <code>{'{COLLEGE_CODE}'}</code>, <code>{'{COLLEGE_ID}'}</code>, <code>{'{YEAR}'}</code>, <code>{'{YY}'}</code>, <code>{'{SESSION_CODE}'}</code>, <code>{'{PROGRAM_CODE}'}</code>, <code>{'{SEQ:6}'}</code>. Student UID and University Roll use College-wide sequences. Class Roll Scope controls whether the sequence runs per Programme Offering or independently per Discipline inside that offering. Changing the scope or format never renumbers existing students; it applies only to future Class Roll assignments.</p>{can.manage&&<Button type="submit" disabled={processing}>{processing&&<Spinner/>}Save Identity Rules</Button>}</div>}</Form></CardContent></Card>
  <Card><CardHeader><CardTitle>Enrolled Students</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-[210px_260px_240px_minmax(260px,1fr)_100px_auto]">
   <Select value={sessionId} onValueChange={v=>{setSessionId(v);setOfferingId('all');setDisciplineId('all');visit({session_id:v,offering_id:null,discipline_id:null},'Loading programme offerings…')}} disabled={loading}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{sessions.map(s=><SelectItem key={s.id} value={String(s.id)}>{s.name}{s.is_current?' · Current':''}</SelectItem>)}</SelectContent></Select>
   <Select value={offeringId} onValueChange={v=>{setOfferingId(v);setDisciplineId('all');visit({offering_id:v==='all'?null:v,discipline_id:null},'Loading disciplines…')}} disabled={loading}><SelectTrigger><SelectValue placeholder="Programme Offering"/></SelectTrigger><SelectContent><SelectItem value="all">All Programme Offerings</SelectItem>{offerings.map(o=><SelectItem key={o.id} value={String(o.id)}>{o.name}{o.code?` (${o.code})`:''}</SelectItem>)}</SelectContent></Select>
   <Select value={disciplineId} onValueChange={v=>{setDisciplineId(v);visit({discipline_id:v==='all'?null:v})}} disabled={loading}><SelectTrigger><SelectValue placeholder="Discipline"/></SelectTrigger><SelectContent><SelectItem value="all">All Disciplines</SelectItem>{disciplines.map(d=><SelectItem key={d.id} value={String(d.id)}>{d.name}{d.code?` (${d.code})`:''}</SelectItem>)}</SelectContent></Select>
   <Input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&visit()} placeholder="Search name / Student UID / University Roll" disabled={loading}/>
   <Select value={perPage} onValueChange={setPerPage} disabled={loading}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[25,50,100].map(n=><SelectItem key={n} value={String(n)}>{n}</SelectItem>)}</SelectContent></Select>
   <Button variant="outline" onClick={()=>visit()} disabled={loading}>{loading?<Spinner/>:<Search className="size-4"/>}Search</Button>
  </div><div className="overflow-x-auto rounded-md border"><table className="w-full min-w-[1000px] text-sm"><thead className="border-b bg-muted/30"><tr>{['Student','Programme','Discipline','Student UID','University Roll No.','Class Roll No.','Status','Action'].map(h=><th key={h} className="px-3 py-2 text-left font-medium">{h}</th>)}</tr></thead><tbody>{students.data.map(r=><tr key={r.id} className="border-b last:border-0"><td className="px-3 py-3 font-medium">{r.name??'—'}</td><td className="px-3 py-3">{r.programme??'—'}<div className="text-xs text-muted-foreground">{r.session??''}</div></td><td className="px-3 py-3">{r.discipline??'—'}{r.discipline_code&&<div className="text-xs text-muted-foreground">{r.discipline_code}</div>}</td><td className="px-3 py-3 font-mono">{r.student_uid??'—'}</td><td className="px-3 py-3 font-mono">{r.university_roll_no??'—'}</td><td className="px-3 py-3 font-mono">{r.class_roll_no??'—'}</td><td className="px-3 py-3">{r.complete?<Badge variant="secondary"><BadgeCheck className="mr-1 size-3"/>Assigned</Badge>:<Badge variant="outline">Pending</Badge>}</td><td className="px-3 py-3">{!r.complete&&can.manage?<Button size="sm" onClick={()=>assign(r)} disabled={loading}><TicketCheck className="size-4"/>Assign</Button>:<span className="text-muted-foreground">—</span>}</td></tr>)}{!students.data.length&&<tr><td colSpan={8} className="px-3 py-10 text-center text-muted-foreground">No enrolled students match the selected filters.</td></tr>}</tbody></table></div>
  <div className="flex flex-wrap items-center justify-between gap-3 text-sm"><span>Showing {students.from??0}-{students.to??0} of {students.total}</span><div className="flex items-center gap-2"><Button size="sm" variant="outline" disabled={loading||!students.prev_page_url} onClick={()=>page(students.prev_page_url)}><ChevronLeft className="size-4"/>Previous</Button><span>Page {students.current_page} of {students.last_page}</span><Button size="sm" variant="outline" disabled={loading||!students.next_page_url} onClick={()=>page(students.next_page_url)}>Next<ChevronRight className="size-4"/></Button></div></div>
  </CardContent></Card>
 </div></>;
}
