import { Form, Head } from '@inertiajs/react';
import { CalendarRange, ChevronDown, ChevronRight, Pencil, Plus, Power, RotateCcw, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { DatePicker } from '@/components/ui/date-picker';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

const selectClass = 'h-10 w-full rounded-md border bg-background px-3 text-sm';

type Session = { id:number; name:string; code:string; starts_on:string; ends_on:string; status:string; is_current:boolean };
type UEvent = { id:number; event_type:string; title:string; start_date:string; end_date:string; description?:string|null; allow_college_override:boolean; status:string; display_order:number };
type UCalendar = { id:number; name:string; code:string; status:string; notes?:string|null; academic_session:Session; events:UEvent[] };
type Override = { id:number; academic_calendar_event_id:number; title:string; start_date:string; end_date:string; description?:string|null; reason:string; status:string };
type CollegeCalendar = { id:number; status:string; notes?:string|null; university_academic_calendar_id:number; university_calendar:UCalendar; overrides:Override[] };
type Can = { create:boolean; update:boolean; enable:boolean; disable:boolean; overrideCreate:boolean; overrideUpdate:boolean; overrideDisable:boolean };
type Props = { college:{id:number;name:string;code:string;status:string}; calendars:CollegeCalendar[]; availableCalendars:UCalendar[]; summary:{total:number;active:number;inactive:number;overrides:number}; can:Can };

function fmtDate(value:string){ const clean=value.slice(0,10); return new Date(clean+'T00:00:00').toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}); }

function AdoptDialog({collegeId, calendars}:{collegeId:number;calendars:UCalendar[]}){
  return <Dialog><DialogTrigger asChild><Button disabled={calendars.length===0}><Plus/>Adopt Calendar</Button></DialogTrigger>
    <DialogContent><DialogHeader><DialogTitle>Adopt University Academic Calendar</DialogTitle><DialogDescription>College Calendar always references the official University calendar for the same Academic Session. It does not copy or redefine University events.</DialogDescription></DialogHeader>
      <Form action={`/college/${collegeId}/academic-calendar`} method="post">{({processing,errors})=><>
        <div className="space-y-4"><div className="space-y-2"><Label>University Academic Calendar</Label><select className={selectClass} name="university_academic_calendar_id" defaultValue="" required><option value="" disabled>Select Academic Session</option>{calendars.map(c=><option key={c.id} value={c.id}>{c.academic_session.name} · {c.name} ({c.code})</option>)}</select>{errors.university_academic_calendar_id&&<p className="text-sm text-destructive">{errors.university_academic_calendar_id}</p>}</div>
        <div className="space-y-2"><Label>College note (optional)</Label><textarea name="notes" className="min-h-20 w-full rounded-md border bg-background px-3 py-2 text-sm" placeholder="Operational note for this College calendar"/></div></div>
        <DialogFooter className="mt-5"><DialogClose asChild><Button type="button" variant="outline">Cancel</Button></DialogClose><Button disabled={processing} type="submit">Adopt Calendar</Button></DialogFooter>
      </>}</Form></DialogContent></Dialog>;
}

function CalendarNoteDialog({collegeId,calendar}:{collegeId:number;calendar:CollegeCalendar}){
 return <Dialog><DialogTrigger asChild><Button size="icon" variant="ghost" title="Edit College calendar note"><Pencil/></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Edit College Calendar Note</DialogTitle><DialogDescription>The Academic Session and University calendar link are inherited and cannot be changed.</DialogDescription></DialogHeader>
 <Form action={`/college/${collegeId}/academic-calendar/${calendar.id}`} method="patch">{({processing})=><><div className="space-y-2"><Label>Note</Label><textarea name="notes" defaultValue={calendar.notes??''} className="min-h-24 w-full rounded-md border bg-background px-3 py-2 text-sm"/></div><DialogFooter className="mt-5"><DialogClose asChild><Button type="button" variant="outline">Cancel</Button></DialogClose><Button disabled={processing}>Save</Button></DialogFooter></>}</Form></DialogContent></Dialog>;
}

function OverrideDialog({collegeId,calendar,event,override}:{collegeId:number;calendar:CollegeCalendar;event:UEvent;override?:Override}){
 const action=override?`/college/${collegeId}/academic-calendar/${calendar.id}/overrides/${override.id}`:`/college/${collegeId}/academic-calendar/${calendar.id}/overrides`;
 const [startDate,setStartDate]=useState((override?.start_date??event.start_date).slice(0,10));
 const [endDate,setEndDate]=useState((override?.end_date??event.end_date).slice(0,10));
 const sessionStart=calendar.university_calendar.academic_session.starts_on.slice(0,10);
 const sessionEnd=calendar.university_calendar.academic_session.ends_on.slice(0,10);
 return <Dialog><DialogTrigger asChild><Button size="sm" variant="outline">{override?<><Pencil/>Edit Override</>:<><Plus/>Override</>}</Button></DialogTrigger><DialogContent className="sm:!max-w-xl"><DialogHeader><DialogTitle>{override?'Edit':'Create'} College Override</DialogTitle><DialogDescription>University allows override for “{event.title}”. The source event remains unchanged and auditable.</DialogDescription></DialogHeader>
 <div className="rounded-md border bg-muted/20 p-3 text-sm"><div className="font-medium">University event</div><div className="text-muted-foreground">{fmtDate(event.start_date)} – {fmtDate(event.end_date)} · {event.event_type}</div></div>
 <Form action={action} method={override?'patch':'post'}>{({processing,errors})=><><input type="hidden" name="academic_calendar_event_id" value={event.id}/><div className="grid gap-4 sm:grid-cols-2">
 <div className="space-y-2 sm:col-span-2"><Label>College event title</Label><Input name="title" defaultValue={override?.title??event.title}/>{errors.title&&<p className="text-sm text-destructive">{errors.title}</p>}</div>
 <div className="space-y-2"><Label>Start date</Label><DatePicker id={`college-calendar-override-${event.id}-start`} name="start_date" value={startDate} onValueChange={value=>{setStartDate(value);if(endDate&&value>endDate)setEndDate(value);}} min={sessionStart} max={sessionEnd} invalid={Boolean(errors.start_date)}/>{errors.start_date&&<p className="text-sm text-destructive">{errors.start_date}</p>}</div>
 <div className="space-y-2"><Label>End date</Label><DatePicker id={`college-calendar-override-${event.id}-end`} name="end_date" value={endDate} onValueChange={setEndDate} min={startDate||sessionStart} max={sessionEnd} invalid={Boolean(errors.end_date)}/>{errors.end_date&&<p className="text-sm text-destructive">{errors.end_date}</p>}</div>
 <div className="space-y-2 sm:col-span-2"><Label>Description (optional)</Label><textarea name="description" defaultValue={override?.description??event.description??''} className="min-h-20 w-full rounded-md border bg-background px-3 py-2 text-sm"/></div>
 <div className="space-y-2 sm:col-span-2"><Label>Override reason</Label><textarea name="reason" required defaultValue={override?.reason??''} className="min-h-20 w-full rounded-md border bg-background px-3 py-2 text-sm" placeholder="Why this College needs a different date/title for this University event"/>{errors.reason&&<p className="text-sm text-destructive">{errors.reason}</p>}</div></div>
 <DialogFooter className="mt-5"><DialogClose asChild><Button type="button" variant="outline">Cancel</Button></DialogClose><Button disabled={processing}>Save Override</Button></DialogFooter></>}</Form></DialogContent></Dialog>;
}

function CalendarCard({collegeId,calendar,can,collegeActive}:{collegeId:number;calendar:CollegeCalendar;can:Can;collegeActive:boolean}){
 const [open,setOpen]=useState(false); const uc=calendar.university_calendar; const activeOverrides=new Map(calendar.overrides.filter(o=>o.status==='ACTIVE').map(o=>[o.academic_calendar_event_id,o]));
 return <Card><CardContent className="p-0"><div className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><CalendarRange className="size-5"/><h2 className="text-lg font-semibold">{uc.academic_session.name}</h2><Badge variant={calendar.status==='ACTIVE'?'default':'secondary'}>{calendar.status}</Badge></div><p className="mt-1 text-sm text-muted-foreground">University source: {uc.name} · {uc.code} · {uc.status}</p><p className="text-xs text-muted-foreground">Session {fmtDate(uc.academic_session.starts_on)} – {fmtDate(uc.academic_session.ends_on)} · {uc.events.length} University events · {activeOverrides.size} active College overrides</p>{calendar.notes&&<p className="mt-2 text-sm">{calendar.notes}</p>}</div>
 <div className="flex gap-2">{can.update&&collegeActive&&<CalendarNoteDialog collegeId={collegeId} calendar={calendar}/>} {collegeActive&&((calendar.status==='ACTIVE'&&can.disable)||(calendar.status==='INACTIVE'&&can.enable))&&<Form action={`/college/${collegeId}/academic-calendar/${calendar.id}/status`} method="patch"><input type="hidden" name="status" value={calendar.status==='ACTIVE'?'INACTIVE':'ACTIVE'}/><Button variant={calendar.status==='ACTIVE'?'outline':'default'}><Power/>{calendar.status==='ACTIVE'?'Deactivate':'Activate'}</Button></Form>}</div></div>
 <button type="button" onClick={()=>setOpen(!open)} className="mt-4 flex w-full items-center justify-between rounded-md border px-3 py-2 text-left text-sm"><span className="flex items-center gap-2">{open?<ChevronDown className="size-4"/>:<ChevronRight className="size-4"/>}<span className="font-medium">Calendar Events</span></span><span className="text-muted-foreground">{uc.events.filter(e=>e.status==='ACTIVE').length} active University events · {activeOverrides.size} overridden</span></button></div>
 {open&&<div className="border-t"><div className="grid grid-cols-[minmax(180px,1.3fr)_minmax(180px,1fr)_130px_minmax(170px,auto)] gap-3 border-b bg-muted/30 px-4 py-2 text-xs font-medium"><span>EVENT</span><span>EFFECTIVE DATE</span><span>GOVERNANCE</span><span className="text-right">ACTIONS</span></div>{uc.events.map(event=>{const override=activeOverrides.get(event.id); const anyOverride=calendar.overrides.find(o=>o.academic_calendar_event_id===event.id); return <div key={event.id} className="grid grid-cols-[minmax(180px,1.3fr)_minmax(180px,1fr)_130px_minmax(170px,auto)] items-center gap-3 border-b px-4 py-3 text-sm last:border-b-0"><div><div className="font-medium">{override?.title??event.title}</div><p className="text-xs text-muted-foreground">{event.event_type} · University: {event.title}{event.status!=='ACTIVE'?' · University event inactive':''}</p>{override&&<p className="mt-1 text-xs text-primary">College override active · Reason: {override.reason}</p>}</div><div><div>{fmtDate((override?.start_date??event.start_date).slice(0,10))} – {fmtDate((override?.end_date??event.end_date).slice(0,10))}</div>{override&&<p className="text-xs text-muted-foreground">University: {fmtDate(event.start_date.slice(0,10))} – {fmtDate(event.end_date.slice(0,10))}</p>}</div><div>{event.allow_college_override?<Badge variant="outline">Override allowed</Badge>:<Badge variant="secondary"><ShieldCheck className="mr-1 size-3"/>University locked</Badge>}</div><div className="flex justify-end gap-2">{collegeActive&&event.status==='ACTIVE'&&event.allow_college_override&&(!anyOverride&&can.overrideCreate)&&<OverrideDialog collegeId={collegeId} calendar={calendar} event={event}/>} {collegeActive&&event.allow_college_override&&anyOverride&&can.overrideUpdate&&<OverrideDialog collegeId={collegeId} calendar={calendar} event={event} override={anyOverride}/>} {collegeActive&&event.allow_college_override&&anyOverride&&can.overrideDisable&&<Form action={`/college/${collegeId}/academic-calendar/${calendar.id}/overrides/${anyOverride.id}/status`} method="patch"><input type="hidden" name="status" value={anyOverride.status==='ACTIVE'?'INACTIVE':'ACTIVE'}/><Button size="sm" variant="outline">{anyOverride.status==='ACTIVE'?<><Power/>Use University</>:<><RotateCcw/>Re-enable</>}</Button></Form>}</div></div>})}</div>}</CardContent></Card>;
}

export default function CollegeAcademicCalendars({college,calendars,availableCalendars,summary,can}:Props){return <><Head title={`${college.name} Academic Calendar`}/><div className="space-y-6 p-4 md:p-6"><header className="flex flex-wrap items-end justify-between gap-3 border-b pb-5"><div><p className="text-sm font-medium text-primary">{college.code} · College Academic Setup</p><h1 className="text-3xl font-semibold">College Academic Calendar</h1><p className="max-w-4xl text-muted-foreground">Adopt the official University Academic Calendar for each Academic Session. University events remain authoritative; a College can change only events explicitly marked “Override allowed” by the University.</p></div>{can.create&&college.status==='ACTIVE'&&<AdoptDialog collegeId={college.id} calendars={availableCalendars}/>}</header>
 {college.status!=='ACTIVE'&&<Card><CardContent className="p-4 text-sm text-muted-foreground">This College is inactive. Existing calendars remain visible but cannot be changed.</CardContent></Card>}
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['College Calendars',summary.total],['Active',summary.active],['Inactive',summary.inactive],['Active Overrides',summary.overrides]].map(([label,value])=><Card key={String(label)}><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></CardContent></Card>)}</div>
 {calendars.length===0?<Card><CardContent className="grid place-items-center py-16 text-center"><CalendarRange className="size-10 text-muted-foreground"/><h2 className="mt-3 font-semibold">No College Academic Calendar Yet</h2><p className="mt-1 max-w-xl text-sm text-muted-foreground">Adopt an ACTIVE University Academic Calendar first. The College does not create an independent calendar disconnected from University governance.</p></CardContent></Card>:<div className="space-y-3">{calendars.map(c=><CalendarCard key={c.id} collegeId={college.id} calendar={c} can={can} collegeActive={college.status==='ACTIVE'}/>)}</div>}</div></>}
